feat(helm-create-flow): add yaml and repository values override
Qovery/console pull request #1010
Opened 2023-12-01 14:38 UTC by RemiBonnet

# What does this PR do?

https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-876

<img width="1761" alt="Capture d’écran 2023-12-05 à 10 09 58" src="https://github.com/Qovery/console/assets/533928/1e3433bf-e066-4b9b-944a-38538b45d495">

<img width="1767" alt="Capture d’écran 2023-12-05 à 10 10 48" src="https://github.com/Qovery/console/assets/533928/3a183f50-c2b5-485d-913c-62d32b78a036">

<img width="1765" alt="Capture d’écran 2023-12-05 à 10 11 15" src="https://github.com/Qovery/console/assets/533928/418bf653-ba2b-4c86-9ab5-1ec02fc5c6e7">

---

## PR Checklist

- [ ] This PR introduces breaking change(s) and has been labeled as such
- [ ] This PR introduces new store changes
- [x] I have followed the library pattern i.e `feature`, `ui`, `data`, `utils`
- [x] I made sure the code is type safe (no any)

2023-12-01 14:38 UTC, acarranoqovery commented
[![Qovery Preview](https://www.qovery.com/images/logo-white.svg)](https://www.qovery.com)
---

Qovery can create a Preview Environment for this PR.
To trigger its creation, please post a comment with one of the following command.

| Command | Blueprint environment |
|---|---|
| /qovery <!-- combo breaker --> preview 28c47145-c8e7-4b9d-8d9e-c65c95b48425 | [staging](https://console.qovery.com/organization/3d542888-3d2c-474a-b1ad-712556db66da/project/a64f6cc1-4e34-433b-b8fd-5359716fb01b/environment/28c47145-c8e7-4b9d-8d9e-c65c95b48425/services/general) |
| /qovery <!-- combo breaker --> preview {all\|UUID1,UUID2,...} | To preview multiple environments |

---

This comment has been generated from [Qovery](https://qovery.com) AI :robot:.
Below, a word from its wisdom :
> One day they will all understand

2023-12-01 14:39 UTC, RemiBonnet commented
/qovery preview 28c47145-c8e7-4b9d-8d9e-c65c95b48425

2023-12-01 14:39 UTC, acarranoqovery commented
[![Qovery Preview](https://www.qovery.com/images/logo-white.svg)](https://www.qovery.com)
---

A preview environment was automatically created via Qovery.
Click on the link below to follow its deployment and use it.
:point_right: [\[PR\] staging - feat(helm-create-flow): add yaml and repository values override - 2023-12-01T14:39:05Z](https://console.qovery.com/organization/3d542888-3d2c-474a-b1ad-712556db66da/project/a64f6cc1-4e34-433b-b8fd-5359716fb01b/environment/997ae960-f32a-4ef0-a005-2b97a2827535/services/general)

 Another comment will be posted when deployments are terminated

2023-12-05 09:13 UTC, RemiBonnet commented on apps/console/src/app/components/preview-code.tsx
> +      readOnly
Adding readOnly params

2023-12-05 09:16 UTC, RemiBonnet commented on libs/pages/services/src/lib/ui/container/container.tsx
> +        {
TODO: comment it after review

2023-12-05 09:17 UTC, RemiBonnet commented on libs/shared/ui/src/lib/components/modal/modal-root.tsx
> +  }, [openModal])
Here we need to reset the context options for Modal during the closing, useEffect is necessary to detect if modal is closed

2023-12-05 15:23 UTC, ctjhoa requested changes

2023-12-05 15:23 UTC, ctjhoa commented on libs/pages/services/src/lib/feature/page-helm-create-feature/step-summary-feature/step-summary-feature.tsx
> +                    ...
`truncateText` already add `...`

2023-12-05 15:23 UTC, ctjhoa commented on libs/domains/service-helm/feature/src/lib/values-override-yaml-modal/values-override-yaml-modal.tsx
> +    async function fetchHelmDefaultValues() {
Hum, this looks weird.
Let's talk about it to see if there is no better solution.

2023-12-06 14:29 UTC, ctjhoa commented on libs/pages/services/src/lib/feature/page-helm-create-feature/step-summary-feature/step-summary-feature.tsx
> +            branch: valuesOverrideFileData.branch!,
optional: refactor to avoid non-null assertion operator

2023-12-06 15:12 UTC, ctjhoa approved these changes

2023-12-06 15:20 UTC, merged

2023-12-12 12:58 UTC, RemiBonnet commented
:tada: This PR is included in version 1.73.0 :tada:

The release is available on [GitHub release](https://github.com/Qovery/console/releases/tag/v1.73.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: