feat(cluster): GCP integration
Qovery/console pull request #1071
Opened 2023-12-28 10:49 UTC by RemiBonnet

# What does this PR do?

https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-947

---

## PR Checklist

- [ ] This PR introduces breaking change(s) and has been labeled as such
- [ ] This PR introduces new store changes
- [x] I have followed the library pattern i.e `feature`, `ui`, `data`, `utils`
- [x] I made sure the code is type safe (no any)

2023-12-28 10:49 UTC, acarranoqovery commented
[![Qovery Preview](https://www.qovery.com/images/logo-white.svg)](https://www.qovery.com)
---

Qovery can create a Preview Environment for this PR.
To trigger its creation, please post a comment with one of the following command.

| Command | Blueprint environment |
|---|---|
| /qovery []() preview 28c47145-c8e7-4b9d-8d9e-c65c95b48425 | [staging](https://console.qovery.com/organization/3d542888-3d2c-474a-b1ad-712556db66da/project/a64f6cc1-4e34-433b-b8fd-5359716fb01b/environment/28c47145-c8e7-4b9d-8d9e-c65c95b48425/services/general) |
| /qovery []() preview {all\|UUID1,UUID2,...} | To preview multiple environments |

---

This comment has been generated from [Qovery](https://qovery.com) AI :robot:.
Below, a word from its wisdom :
> Make it work, make it right, make it fast

2023-12-28 13:43 UTC, RemiBonnet commented on libs/pages/clusters/src/lib/ui/page-clusters-create/step-general/step-general.tsx
> -        .filter((value) => value.value !== CloudProviderEnum.GCP),
Don't forget to keep it before merging

2023-12-28 13:44 UTC, RemiBonnet commented
/qovery preview 28c47145-c8e7-4b9d-8d9e-c65c95b48425

2023-12-28 13:47 UTC, RemiBonnet commented
/qovery preview 28c47145-c8e7-4b9d-8d9e-c65c95b48425

2023-12-28 14:02 UTC, mzottola commented
/qovery preview 28c47145-c8e7-4b9d-8d9e-c65c95b48425

2023-12-28 14:02 UTC, acarranoqovery commented
[![Qovery Preview](https://www.qovery.com/images/logo-white.svg)](https://www.qovery.com)
---

A preview environment was automatically created via Qovery.
Click on the link below to follow its deployment and use it.
:point_right: [\[PR\] staging - feat(cluster): GCP integration - 2023-12-28T14:02:57Z](https://console.qovery.com/organization/3d542888-3d2c-474a-b1ad-712556db66da/project/a64f6cc1-4e34-433b-b8fd-5359716fb01b/environment/aecc4656-5cea-4844-81af-ab3629ce82d3/services/general)

 Another comment will be posted when deployments are terminated

2023-12-28 14:08 UTC, acarranoqovery commented
[![Qovery Preview](https://www.qovery.com/images/logo-white.svg)](https://www.qovery.com)
---

Your preview environment has been successfully deployed !
Click on the link below to open your service:
:point_right: [console](https://1071-console-staging.zc531a994.rustrocks.cloud)

2023-12-29 09:10 UTC, ctjhoa requested changes

2023-12-29 09:10 UTC, ctjhoa commented on libs/shared/console-shared/src/lib/flow-create-port/ui/crud-modal/crud-modal.tsx
> +  console.log(protocolOptions)
to remove

2023-12-29 09:10 UTC, ctjhoa commented on libs/shared/console-shared/src/lib/flow-create-port/ui/crud-modal/crud-modal.tsx
> +  console.log(cloudProvider)
to remove

2023-12-29 09:10 UTC, ctjhoa commented on libs/shared/console-shared/src/lib/application-settings/ui/application-settings-resources/application-settings-resources.tsx
> +  const { data: environment } = useFetchEnvironment(projectId, environmentId)
use `useEnvironment` from `@qovery/domains/environments/feature'` instead of `useFetchEnvironment`

2023-12-29 09:10 UTC, ctjhoa commented on libs/pages/clusters/src/lib/feature/page-clusters-create-feature/page-clusters-create-feature.tsx
> +  } else if (cloudProvider === CloudProviderEnum.GCP) {
This `if` chain should be transform into ts-pattern `match`

2023-12-29 09:50 UTC, ctjhoa approved these changes

2024-01-05 09:42 UTC, merged

2024-01-08 13:59 UTC, RemiBonnet commented
:tada: This PR is included in version 1.79.0 :tada:

The release is available on [GitHub release](https://github.com/Qovery/console/releases/tag/v1.79.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: