feat(services): add helm advanced settings
Qovery/console pull request #1076
Opened 2023-12-28 16:59 UTC by ctjhoa

# What does this PR do?

https://qovery.atlassian.net/browse/FRT-941

2023-12-28 16:59 UTC, acarranoqovery commented
[![Qovery Preview](https://www.qovery.com/images/logo-white.svg)](https://www.qovery.com)
---

Qovery can create a Preview Environment for this PR.
To trigger its creation, please post a comment with one of the following command.

| Command | Blueprint environment |
|---|---|
| /qovery []() preview 28c47145-c8e7-4b9d-8d9e-c65c95b48425 | [staging](https://console.qovery.com/organization/3d542888-3d2c-474a-b1ad-712556db66da/project/a64f6cc1-4e34-433b-b8fd-5359716fb01b/environment/28c47145-c8e7-4b9d-8d9e-c65c95b48425/services/general) |
| /qovery []() preview {all\|UUID1,UUID2,...} | To preview multiple environments |

---

This comment has been generated from [Qovery](https://qovery.com) AI :robot:.
Below, a word from its wisdom :
> You are going to thank you later if it contains tests

2023-12-29 09:08 UTC, RemiBonnet requested changes

2023-12-29 13:31 UTC, ctjhoa commented on libs/pages/application/src/lib/feature/page-settings-advanced-feature/page-settings-advanced-feature.tsx
> +            <h1 className="h5 text-neutral-400 mb-2">Advanced Settings</h1>
Nope I can't because all settings page title like that. Otherwise this page will have a title different from the others.

2023-12-29 13:32 UTC, ctjhoa commented on libs/pages/application/src/lib/feature/page-settings-advanced-feature/page-settings-advanced-feature.tsx
> +  const { data: advancedSettings } = useAdvancedSettings({ serviceId, serviceType })
No I can't because `defaultAdvancedSettings`  and `advancedSettings` must be defined for the underlying `useForm` `defaultValues`.

2023-12-29 13:36 UTC, ctjhoa commented on libs/domains/services/feature/src/lib/advanced-settings/advanced-settings.tsx
> +  const table = useReactTable({
`react-table` is great for type safety even for simple cases. I don't see benefits of not using it.

2023-12-29 13:37 UTC, ctjhoa commented on libs/domains/services/feature/src/lib/advanced-settings/advanced-settings.tsx
> +function formatValue(value: any) {
Yes you're right
https://github.com/Qovery/console/pull/1076/commits/ad452a82b81cd994d6fa49686b96b239251a8fea

2023-12-29 16:04 UTC, RemiBonnet commented on libs/pages/application/src/lib/feature/page-settings-advanced-feature/page-settings-advanced-feature.tsx
> +  const { data: advancedSettings } = useAdvancedSettings({ serviceId, serviceType })
The `useForm` is inside your `<AdvancedSettings />` component for me the hooks should be inside as well

2023-12-29 16:08 UTC, RemiBonnet commented on libs/pages/application/src/lib/feature/page-settings-advanced-feature/page-settings-advanced-feature.tsx
> +            <h1 className="h5 text-neutral-400 mb-2">Advanced Settings</h1>
We have already do that for `Networking` `Values override` I think you start to add it as well, we will harmonize afterwards

2023-12-29 16:11 UTC, RemiBonnet requested changes

2023-12-29 16:11 UTC, RemiBonnet commented on libs/pages/application/src/lib/feature/page-settings-advanced-feature/page-settings-advanced-feature.tsx
> +  const { data: advancedSettings } = useAdvancedSettings({ serviceId, serviceType })
The `useForm` is inside your `<AdvancedSettings />` component for me the hooks should be inside as well

2023-12-29 16:11 UTC, RemiBonnet commented on libs/pages/application/src/lib/feature/page-settings-advanced-feature/page-settings-advanced-feature.tsx
> +            <h1 className="h5 text-neutral-400 mb-2">Advanced Settings</h1>
We have already do that for `Networking` `Values override`, I think you start to add it as well, we will harmonize afterwards

2024-01-02 09:24 UTC, ctjhoa commented on libs/pages/application/src/lib/feature/page-settings-advanced-feature/page-settings-advanced-feature.tsx
> +            <h1 className="h5 text-neutral-400 mb-2">Advanced Settings</h1>
Fixed
https://github.com/Qovery/console/pull/1076/commits/9d1546d4016d8f5ed0fe5840187c17f146c68ae5

2024-01-02 09:31 UTC, RemiBonnet approved these changes

2024-01-02 10:55 UTC, merged

2024-01-04 10:02 UTC, RemiBonnet commented
:tada: This PR is included in version 1.78.0 :tada:

The release is available on [GitHub release](https://github.com/Qovery/console/releases/tag/v1.78.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: