feat(service): migration database to react-query
Qovery/console pull request #1078
Opened 2023-12-29 14:17 UTC by RemiBonnet

# What does this PR do?

- Remove domain `@qovery/domains/database` 
- Add new common hook `createService` 

https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-920

---

## PR Checklist

- [ ] This PR introduces breaking change(s) and has been labeled as such
- [ ] This PR introduces new store changes
- [x] I have followed the library pattern i.e `feature`, `ui`, `data`, `utils`
- [x] I made sure the code is type safe (no any)

2023-12-29 14:17 UTC, acarranoqovery commented
[![Qovery Preview](https://www.qovery.com/images/logo-white.svg)](https://www.qovery.com)
---

Qovery can create a Preview Environment for this PR.
To trigger its creation, please post a comment with one of the following command.

| Command | Blueprint environment |
|---|---|
| /qovery []() preview 28c47145-c8e7-4b9d-8d9e-c65c95b48425 | [staging](https://console.qovery.com/organization/3d542888-3d2c-474a-b1ad-712556db66da/project/a64f6cc1-4e34-433b-b8fd-5359716fb01b/environment/28c47145-c8e7-4b9d-8d9e-c65c95b48425/services/general) |
| /qovery []() preview {all\|UUID1,UUID2,...} | To preview multiple environments |

---

This comment has been generated from [Qovery](https://qovery.com) AI :robot:.
Below, a word from its wisdom :
> Help yourself at 2AM by putting some metrics to help observability

2024-01-02 07:58 UTC, ctjhoa requested changes

2024-01-02 07:58 UTC, ctjhoa commented on libs/domains/cloud-providers/data-access/src/lib/domains-cloud-providers-data-access.ts
> +          if (!region) throw new Error('Region is required for AWS')
enforce region via types cf `listInstanceTypes`

2024-01-02 07:58 UTC, ctjhoa commented on libs/domains/cloud-providers/feature/src/lib/hooks/use-cloud-provider-database-instance-types/use-cloud-provider-database-instance-types.tsx
> +export function useCloudProviderDatabaseInstanceTypes({
Once region is enforced by typing you can reuse the data-access param (cf. `useCloudProviderInstanceTypes`)

2024-01-02 07:58 UTC, ctjhoa commented on libs/domains/services/data-access/src/lib/domains-services-data-access.ts
> +      .with({ serviceType: 'HELM' }, (payload) => helmsApi.createHelm.bind(helmsApi, environmentId, payload))
return a new object including `serviceType` to avoid `mutation` typing issue

2024-01-02 07:58 UTC, ctjhoa commented on libs/domains/services/data-access/src/lib/domains-services-data-access.ts
> +      .with('HELM', () => helmActionsApi.restartHelm.bind(helmActionsApi))
return a new object including `serviceType` to avoid `mutation` typing issue

2024-01-02 07:58 UTC, ctjhoa commented on libs/domains/services/feature/src/lib/hooks/use-create-service/use-create-service.ts
> +        title: `Your database has been created`,
```suggestion
        title: `Your service has been created`,
```

2024-01-02 07:58 UTC, ctjhoa commented on libs/domains/services/feature/src/lib/service-action-toolbar/service-action-toolbar.tsx
> +import useRunningStatus from '../hooks/use-running-status/use-running-status'
```suggestion
import { useRunningStatus } from '../hooks/use-running-status/use-running-status'
```

2024-01-02 07:58 UTC, ctjhoa commented on libs/domains/services/feature/src/lib/service-action-toolbar/service-action-toolbar.tsx
> +import useRestartService from '../hooks/use-restart-service/use-restart-service'
```suggestion
import { useRestartService } from '../hooks/use-restart-service/use-restart-service'
```

2024-01-02 07:58 UTC, ctjhoa commented on libs/domains/services/feature/src/lib/service-list/service-list.tsx
> +            .with('DATABASE', () => <ServiceActionToolbar serviceId={service.id} />)
```suggestion
            .with('HELM', 'DATABASE', () => <ServiceActionToolbar serviceId={service.id} />)
```

2024-01-02 10:59 UTC, ctjhoa approved these changes

2024-01-02 11:00 UTC, merged

2024-01-04 10:01 UTC, RemiBonnet commented
:tada: This PR is included in version 1.78.0 :tada:

The release is available on [GitHub release](https://github.com/Qovery/console/releases/tag/v1.78.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: