feat(custom-domain): add react query
Qovery/console pull request #1084
Opened 2024-01-02 16:12 UTC by RemiBonnet

# What does this PR do?

> Link to the JIRA ticket

Put description here

> Screenshot of the feature

---

## PR Checklist

- [ ] This PR introduces breaking change(s) and has been labeled as such
- [ ] This PR introduces new store changes
- [ ] I have followed the library pattern i.e `feature`, `ui`, `data`, `utils`
- [ ] I made sure the code is type safe (no any)

2024-01-02 16:12 UTC, acarranoqovery commented
[![Qovery Preview](https://www.qovery.com/images/logo-white.svg)](https://www.qovery.com)
---

Qovery can create a Preview Environment for this PR.
To trigger its creation, please post a comment with one of the following command.

| Command | Blueprint environment |
|---|---|
| /qovery []() preview 28c47145-c8e7-4b9d-8d9e-c65c95b48425 | [staging](https://console.qovery.com/organization/3d542888-3d2c-474a-b1ad-712556db66da/project/a64f6cc1-4e34-433b-b8fd-5359716fb01b/environment/28c47145-c8e7-4b9d-8d9e-c65c95b48425/services/general) |
| /qovery []() preview {all\|UUID1,UUID2,...} | To preview multiple environments |

---

This comment has been generated from [Qovery](https://qovery.com) AI :robot:.
Below, a word from its wisdom :
> Take rest sometimes

2024-01-02 16:49 UTC, RemiBonnet commented on libs/pages/application/src/lib/ui/page-settings-domains/input-approval-badge/input-approval-badge.tsx
useless component

2024-01-03 10:54 UTC, ctjhoa requested changes

2024-01-03 10:54 UTC, ctjhoa commented on libs/domains/services/data-access/src/lib/domains-services-data-access.ts
> +    const response = await mutation()
You can pass `serviceId`, `customDomainId` and `payload` here because they are not type dependent

2024-01-03 10:54 UTC, ctjhoa commented on libs/domains/services/data-access/src/lib/domains-services-data-access.ts
> +    const response = await mutation()
You can pass `serviceId` and `customDomainId` here because they are not type dependent

2024-01-03 10:54 UTC, ctjhoa commented on libs/pages/application/src/lib/feature/page-settings-domains-feature/crud-modal-feature/crud-modal-feature.tsx
> +  service?: AnyService
It should be better to limit `serviceType` here so you are guarantee about the `serviceType` everywhere and you can handle wrong serviceType in `PageSettingsDomainsFeature` using `redirect` or whatever.
You can also handle `undefined` service upfront

2024-01-03 17:11 UTC, ctjhoa approved these changes

2024-01-03 17:18 UTC, merged

2024-01-04 10:01 UTC, RemiBonnet commented
:tada: This PR is included in version 1.78.0 :tada:

The release is available on [GitHub release](https://github.com/Qovery/console/releases/tag/v1.78.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: