feat(services): add helm deploy other version
Qovery/console pull request #1088
Opened 2024-01-03 16:52 UTC by ctjhoa

# What does this PR do?

https://qovery.atlassian.net/browse/FRT-954

2024-01-03 16:52 UTC, acarranoqovery commented
[![Qovery Preview](https://www.qovery.com/images/logo-white.svg)](https://www.qovery.com)
---

Qovery can create a Preview Environment for this PR.
To trigger its creation, please post a comment with one of the following command.

| Command | Blueprint environment |
|---|---|
| /qovery []() preview 28c47145-c8e7-4b9d-8d9e-c65c95b48425 | [staging](https://console.qovery.com/organization/3d542888-3d2c-474a-b1ad-712556db66da/project/a64f6cc1-4e34-433b-b8fd-5359716fb01b/environment/28c47145-c8e7-4b9d-8d9e-c65c95b48425/services/general) |
| /qovery []() preview {all\|UUID1,UUID2,...} | To preview multiple environments |

---

This comment has been generated from [Qovery](https://qovery.com) AI :robot:.
Below, a word from its wisdom :
> Write comments that add new information that doesn’t exist in the code

2024-01-04 09:53 UTC, RemiBonnet requested changes

2024-01-04 09:53 UTC, RemiBonnet commented on libs/domains/services/feature/src/lib/select-commit-modal/select-commit-modal.tsx
> +        <h2 className="h4 text-neutral-400 max-w-sm truncate mb-1">{title}</h2>
```suggestion
        <h2 className="h4 text-neutral-400 max-w-sm truncate">{title}</h2>
```

2024-01-04 09:53 UTC, RemiBonnet commented on libs/domains/services/feature/src/lib/select-commit-modal/select-commit-modal.tsx
> +        <p>{description}</p>
```suggestion
        <p className="text-neutral-350">{description}</p>
```

2024-01-04 09:53 UTC, RemiBonnet commented on libs/domains/services/feature/src/lib/select-version-modal/select-version-modal.tsx
> +        <p>{description}</p>
```suggestion
        <p className="text-neutral-350">{description}</p>
```

2024-01-04 16:29 UTC, ctjhoa commented on libs/domains/services/feature/src/lib/select-commit-modal/select-commit-modal.tsx
> +import * as RadioGroup from '@radix-ui/react-radio-group'
https://github.com/Qovery/console/pull/1088/commits/75c962c05de1506990c949c6638d2836f324f2c5

2024-01-04 16:29 UTC, ctjhoa commented on libs/domains/services/feature/src/lib/select-commit-modal/select-commit-modal.tsx
> +                            'flex flex-row gap-3 w-full w-full p-3 border border-neutral-250 -mt-px first:rounded-t-md last:rounded-b-md',
https://github.com/Qovery/console/pull/1088/commits/3867e9b0824951b0bbfb367578bb46dd55481757

2024-01-04 16:29 UTC, ctjhoa commented on libs/domains/services/feature/src/lib/select-commit-modal/select-commit-modal.tsx
> +                  Commit{commits.length > 1 ? 's' : ''} on {dateToFormat(date, 'MMM dd, yyyy')}
https://github.com/Qovery/console/pull/1088/commits/76a9eda0f3a87542d666d3add6d7c1d42434dca7

2024-01-04 16:30 UTC, ctjhoa commented on libs/domains/services/feature/src/lib/select-version-modal/select-version-modal.spec.tsx
> +  it('should match snapshot', () => {
This is not needed because it's the `SelectVersionModal` not the `SelectCommitModal`. We don't fetch any version list here, it's only an input text.

2024-01-04 16:31 UTC, ctjhoa commented on libs/domains/services/feature/src/lib/select-commit-modal/select-commit-modal.tsx
> +        <p>{description}</p>
https://github.com/Qovery/console/pull/1088/commits/6eddece68d3a58d79e7a2e4629d958cbf0a1b1e6

2024-01-04 16:31 UTC, ctjhoa commented on libs/domains/services/feature/src/lib/select-commit-modal/select-commit-modal.tsx
> +        <h2 className="h4 text-neutral-400 max-w-sm truncate mb-1">{title}</h2>
https://github.com/Qovery/console/pull/1088/commits/6eddece68d3a58d79e7a2e4629d958cbf0a1b1e6

2024-01-04 16:31 UTC, ctjhoa commented on libs/domains/services/feature/src/lib/select-version-modal/select-version-modal.tsx
> +        <p>{description}</p>
https://github.com/Qovery/console/pull/1088/commits/eb50d3fb066d4c34bb87d142424b0ec507980f6e

2024-01-04 16:32 UTC, ctjhoa commented on libs/domains/services/feature/src/lib/select-commit-modal/select-commit-modal.tsx
> +                                <Icon name={IconAwesomeEnum.CHECK} className="" />
https://github.com/Qovery/console/pull/1088/commits/c02fd04131a907d6b98bcbddb34a4d2e3da6a258

2024-01-04 16:33 UTC, ctjhoa commented
![2024-01-04-170646_732x388_scrot](https://github.com/Qovery/console/assets/1716173/8c5f8e27-7b7c-4a07-aaaf-1a435c19fce9)

2024-01-04 19:14 UTC, RemiBonnet commented on libs/domains/services/feature/src/lib/select-version-modal/select-version-modal.spec.tsx
> +  it('should match snapshot', () => {
oh ok my bad!

2024-01-04 19:14 UTC, RemiBonnet approved these changes

2024-01-05 08:45 UTC, merged

2024-01-08 13:59 UTC, RemiBonnet commented
:tada: This PR is included in version 1.79.0 :tada:

The release is available on [GitHub release](https://github.com/Qovery/console/releases/tag/v1.79.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: