feat(services): migrate ports react query
Qovery/console pull request #1089
Opened 2024-01-03 17:09 UTC by RemiBonnet

# What does this PR do?

https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-920

---

## PR Checklist

- [ ] This PR introduces breaking change(s) and has been labeled as such
- [ ] This PR introduces new store changes
- [x] I have followed the library pattern i.e `feature`, `ui`, `data`, `utils`
- [x] I made sure the code is type safe (no any)

2024-01-03 17:09 UTC, acarranoqovery commented
[![Qovery Preview](https://www.qovery.com/images/logo-white.svg)](https://www.qovery.com)
---

Qovery can create a Preview Environment for this PR.
To trigger its creation, please post a comment with one of the following command.

| Command | Blueprint environment |
|---|---|
| /qovery []() preview 28c47145-c8e7-4b9d-8d9e-c65c95b48425 | [staging](https://console.qovery.com/organization/3d542888-3d2c-474a-b1ad-712556db66da/project/a64f6cc1-4e34-433b-b8fd-5359716fb01b/environment/28c47145-c8e7-4b9d-8d9e-c65c95b48425/services/general) |
| /qovery []() preview {all\|UUID1,UUID2,...} | To preview multiple environments |

---

This comment has been generated from [Qovery](https://qovery.com) AI :robot:.
Below, a word from its wisdom :
> Programs must be written for people to read, and only incidentally for machines to execute

2024-01-03 17:48 UTC, ctjhoa requested changes

2024-01-03 17:48 UTC, ctjhoa commented on libs/pages/services/src/lib/feature/page-settings-preview-environments-feature/page-settings-preview-environments-feature.tsx
> +      services?.forEach(async (service: AnyService) => {
```suggestion
      services.forEach(async (service: AnyService) => {
```

2024-01-03 17:48 UTC, ctjhoa commented on libs/pages/services/src/lib/feature/page-settings-preview-environments-feature/page-settings-preview-environments-feature.tsx
> +          if (!payload) return
```suggestion
            .exhaustive()
```
as you have handle `DATABASE` type upfront it should be fine

2024-01-03 17:48 UTC, ctjhoa commented on libs/pages/services/src/lib/feature/page-settings-preview-environments-feature/page-settings-preview-environments-feature.tsx
> +      services?.forEach((service) => methods.setValue(service.id, value, { shouldDirty: true }))
```suggestion
      services.forEach((service) => methods.setValue(service.id, value, { shouldDirty: true }))
```

2024-01-03 17:48 UTC, ctjhoa commented on libs/pages/services/src/lib/feature/page-settings-preview-environments-feature/page-settings-preview-environments-feature.tsx
> +      services?.forEach((service) =>
```suggestion
      services.forEach((service) =>
```

2024-01-03 17:48 UTC, ctjhoa commented on libs/pages/services/src/lib/ui/page-settings-preview-environments/page-settings-preview-environments.tsx
> +  services?: AnyService[]
```suggestion
  services: AnyService[]
```

2024-01-03 17:48 UTC, ctjhoa commented on libs/pages/services/src/lib/ui/page-settings-preview-environments/page-settings-preview-environments.tsx
> +              {services?.map(
```suggestion
              {services.map(
```

2024-01-03 17:48 UTC, ctjhoa commented on libs/pages/services/src/lib/ui/page-settings-preview-environments/page-settings-preview-environments.tsx
> +              {services && services.length > 0 && (
```suggestion
              {services.length > 0 && (
```

2024-01-04 08:43 UTC, ctjhoa approved these changes

2024-01-04 08:44 UTC, merged

2024-01-04 10:01 UTC, RemiBonnet commented
:tada: This PR is included in version 1.78.0 :tada:

The release is available on [GitHub release](https://github.com/Qovery/console/releases/tag/v1.78.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: