feat(services): migrate storage setting react query
Qovery/console pull request #1097
Opened 2024-01-05 09:29 UTC by RemiBonnet

# What does this PR do?

https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-920

---

## PR Checklist

- [ ] This PR introduces breaking change(s) and has been labeled as such
- [ ] This PR introduces new store changes
- [x] I have followed the library pattern i.e `feature`, `ui`, `data`, `utils`
- [x] I made sure the code is type safe (no any)

2024-01-05 09:29 UTC, acarranoqovery commented
[![Qovery Preview](https://www.qovery.com/images/logo-white.svg)](https://www.qovery.com)
---

Qovery can create a Preview Environment for this PR.
To trigger its creation, please post a comment with one of the following command.

| Command | Blueprint environment |
|---|---|
| /qovery []() preview 28c47145-c8e7-4b9d-8d9e-c65c95b48425 | [staging](https://console.qovery.com/organization/3d542888-3d2c-474a-b1ad-712556db66da/project/a64f6cc1-4e34-433b-b8fd-5359716fb01b/environment/28c47145-c8e7-4b9d-8d9e-c65c95b48425/services/general) |
| /qovery []() preview {all\|UUID1,UUID2,...} | To preview multiple environments |

---

This comment has been generated from [Qovery](https://qovery.com) AI :robot:.
Below, a word from its wisdom :
> Write comments that add new information that doesn’t exist in the code

2024-01-05 11:50 UTC, RemiBonnet commented on libs/shared/util-services/src/lib/build-edit-service-payload.ts
> +    registry_id: container.registry_id || container.registry?.id || '',
I have a special case here, that's why I added `container.registry?.id`, I think Container detail return an `registry` object

2024-01-05 15:42 UTC, ctjhoa requested changes

2024-01-05 15:42 UTC, ctjhoa commented on libs/pages/application/src/lib/feature/page-settings-storage-feature/storage-modal-feature/storage-modal-feature.tsx
> +  service: Extract<AnyService, Application | Container>
```suggestion
  service: Application | Container
```

2024-01-05 15:51 UTC, RemiBonnet commented on libs/pages/application/src/lib/feature/page-settings-storage-feature/storage-modal-feature/storage-modal-feature.tsx
> +  service: Extract<AnyService, Application | Container>
https://github.com/Qovery/console/pull/1097/commits/4a9b27bdd92080b60e252a2402f58e2946751eee

2024-01-05 15:52 UTC, ctjhoa approved these changes

2024-01-05 15:56 UTC, merged

2024-01-08 13:58 UTC, RemiBonnet commented
:tada: This PR is included in version 1.79.0 :tada:

The release is available on [GitHub release](https://github.com/Qovery/console/releases/tag/v1.79.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: