feat(services): migrate resources setting react query
Qovery/console pull request #1099
Opened 2024-01-05 15:23 UTC by RemiBonnet

# What does this PR do?

https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-920

---

## PR Checklist

- [ ] This PR introduces breaking change(s) and has been labeled as such
- [ ] This PR introduces new store changes
- [x] I have followed the library pattern i.e `feature`, `ui`, `data`, `utils`
- [x] I made sure the code is type safe (no any)

2024-01-05 15:23 UTC, RemiBonnet commented
[![Qovery Preview](https://www.qovery.com/images/logo-white.svg)](https://www.qovery.com)
---

Qovery can create a Preview Environment for this PR.
To trigger its creation, please post a comment with one of the following command.

| Command | Blueprint environment |
|---|---|
| /qovery []() preview cc1de7de-94e5-40f8-8e45-bc8986d9dfec | [storybook](https://console.qovery.com/organization/3d542888-3d2c-474a-b1ad-712556db66da/project/a64f6cc1-4e34-433b-b8fd-5359716fb01b/environment/cc1de7de-94e5-40f8-8e45-bc8986d9dfec/services/general) |
 /qovery []() preview 28c47145-c8e7-4b9d-8d9e-c65c95b48425 | [staging](https://console.qovery.com/organization/3d542888-3d2c-474a-b1ad-712556db66da/project/a64f6cc1-4e34-433b-b8fd-5359716fb01b/environment/28c47145-c8e7-4b9d-8d9e-c65c95b48425/services/general) |
| /qovery []() preview {all\|UUID1,UUID2,...} | To preview multiple environments |

---

This comment has been generated from [Qovery](https://qovery.com) AI :robot:.
Below, a word from its wisdom :
> Make it work, make it right, make it fast

2024-01-05 15:41 UTC, ctjhoa requested changes

2024-01-05 15:41 UTC, ctjhoa commented on libs/pages/application/src/lib/feature/page-settings-resources-feature/page-settings-resources-feature.tsx
> +  service: Exclude<AnyService, Helm | Database>
```suggestion
  service: Helm | Database
```

2024-01-05 15:41 UTC, ctjhoa commented on libs/pages/application/src/lib/ui/page-settings-resources/page-settings-resources.tsx
> +  service: Exclude<AnyService, Helm | Database>
```suggestion
  service: Helm | Database
```

2024-01-05 15:41 UTC, ctjhoa commented on libs/shared/console-shared/src/lib/application-settings/ui/application-settings-resources/application-settings-resources.tsx
> +  service?: Exclude<AnyService, Helm | Database>
```suggestion
  service: Helm | Database
```
and you can remove all `service` null checks

2024-01-05 15:50 UTC, ctjhoa commented on libs/pages/application/src/lib/feature/page-settings-resources-feature/page-settings-resources-feature.tsx
> +  service: Exclude<AnyService, Helm | Database>
ok seens it's Exclude my bad

2024-01-05 15:50 UTC, ctjhoa commented on libs/shared/console-shared/src/lib/application-settings/ui/application-settings-resources/application-settings-resources.tsx
> +  service?: Exclude<AnyService, Helm | Database>
ok seens it's Exclude my bad

2024-01-05 15:51 UTC, ctjhoa approved these changes

2024-01-05 15:52 UTC, merged

2024-01-08 13:58 UTC, RemiBonnet commented
:tada: This PR is included in version 1.79.0 :tada:

The release is available on [GitHub release](https://github.com/Qovery/console/releases/tag/v1.79.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: