feat(cluster-credential): add upload file field for GCP
Qovery/console pull request #1107
Opened 2024-01-09 17:09 UTC by RemiBonnet

# What does this PR do?

https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-965

---

## PR Checklist

- [ ] This PR introduces breaking change(s) and has been labeled as such
- [ ] This PR introduces new store changes
- [x] I have followed the library pattern i.e `feature`, `ui`, `data`, `utils`
- [x] I made sure the code is type safe (no any)

2024-01-10 13:32 UTC, ctjhoa requested changes

2024-01-10 13:32 UTC, ctjhoa commented on libs/shared/console-shared/src/lib/cluster-settings/ui/create-edit-credentials-modal/create-edit-credentials-modal.tsx
> +    onDrop: (acceptedFiles) => {
```suggestion
    maxFiles: 1,
    onDrop: (acceptedFiles) => {
```

2024-01-10 14:03 UTC, RemiBonnet commented on libs/shared/console-shared/src/lib/cluster-settings/ui/create-edit-credentials-modal/create-edit-credentials-modal.tsx
> +    onDrop: (acceptedFiles) => {
https://github.com/Qovery/console/pull/1107/commits/4aa33ca1d2431d349ad74a0969c5377c7dbd06ac

2024-01-10 14:15 UTC, ctjhoa approved these changes

2024-01-10 14:35 UTC, merged

2024-01-11 13:32 UTC, RemiBonnet commented
:tada: This PR is included in version 1.82.0 :tada:

The release is available on [GitHub release](https://github.com/Qovery/console/releases/tag/v1.82.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: