feat(userSignUp): migrate react query
Qovery/console pull request #1124
Opened 2024-01-15 10:13 UTC by RemiBonnet

# What does this PR do?

> Link to the JIRA ticket

Put description here

> Screenshot of the feature

---

## PR Checklist

- [ ] This PR introduces breaking change(s) and has been labeled as such
- [ ] This PR introduces new store changes
- [ ] I have followed the library pattern i.e `feature`, `ui`, `data`, `utils`
- [ ] I made sure the code is type safe (no any)

2024-01-15 10:13 UTC, RemiBonnet commented
[![Qovery Preview](https://www.qovery.com/images/logo-white.svg)](https://www.qovery.com)
---

Qovery can create a Preview Environment for this PR.
To trigger its creation, please post a comment with one of the following command.

| Command | Blueprint environment |
|---|---|
| /qovery []() preview 28102cd2-684e-4ecb-a4f7-2f37f653b027 | [my-helm-env](https://console.qovery.com/organization/3d542888-3d2c-474a-b1ad-712556db66da/project/e773b890-e6b2-4406-93a9-71f9a7ab6d73/environment/28102cd2-684e-4ecb-a4f7-2f37f653b027/services/general) |
 /qovery []() preview cc1de7de-94e5-40f8-8e45-bc8986d9dfec | [storybook](https://console.qovery.com/organization/3d542888-3d2c-474a-b1ad-712556db66da/project/a64f6cc1-4e34-433b-b8fd-5359716fb01b/environment/cc1de7de-94e5-40f8-8e45-bc8986d9dfec/services/general) |
 /qovery []() preview 28c47145-c8e7-4b9d-8d9e-c65c95b48425 | [staging](https://console.qovery.com/organization/3d542888-3d2c-474a-b1ad-712556db66da/project/a64f6cc1-4e34-433b-b8fd-5359716fb01b/environment/28c47145-c8e7-4b9d-8d9e-c65c95b48425/services/general) |
| /qovery []() preview {all\|UUID1,UUID2,...} | To preview multiple environments |

---

This comment has been generated from [Qovery](https://qovery.com) AI :robot:.
Below, a word from its wisdom :
> Programs must be written for people to read, and only incidentally for machines to execute

2024-01-15 16:38 UTC, ctjhoa requested changes

2024-01-15 16:38 UTC, ctjhoa commented on libs/domains/cloud-providers/data-access/src/lib/domains-cloud-providers-data-access.ts
> +type DistributiveOmit<T, K extends keyof T> = T extends unknown ? Omit<T, K> : never
use 
```
import { type DistributiveOmit } from '@qovery/shared/util-types'
```
instead.

2024-01-15 16:38 UTC, ctjhoa commented on libs/pages/onboarding/src/lib/feature/onboarding-more/onboarding-more.tsx
> +        } else if (!userSignUp?.dx_auth) {
```suggestion
        } else {
```
?

2024-01-15 17:04 UTC, RemiBonnet commented on libs/pages/onboarding/src/lib/feature/onboarding-more/onboarding-more.tsx
> +        } else if (!userSignUp?.dx_auth) {
https://github.com/Qovery/console/pull/1124/commits/548c6c007285939fd53eb89c1fd78345b0bdbff7

2024-01-15 17:04 UTC, RemiBonnet commented on libs/domains/cloud-providers/data-access/src/lib/domains-cloud-providers-data-access.ts
> +type DistributiveOmit<T, K extends keyof T> = T extends unknown ? Omit<T, K> : never
https://github.com/Qovery/console/pull/1124/commits/548c6c007285939fd53eb89c1fd78345b0bdbff7

2024-01-16 09:07 UTC, ctjhoa approved these changes

2024-01-16 09:14 UTC, merged

2024-01-16 09:57 UTC, RemiBonnet commented
:tada: This PR is included in version 1.84.0 :tada:

The release is available on [GitHub release](https://github.com/Qovery/console/releases/tag/v1.84.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: