feat(environments): add new hooks and data-accesses
Qovery/console pull request #1233
Opened 2024-03-06 16:35 UTC by ctjhoa

# What does this PR do?

https://qovery.atlassian.net/browse/FRT-1044

2024-03-06 16:35 UTC, RemiBonnet commented
[![Qovery Preview](https://www.qovery.com/images/logo-white.svg)](https://www.qovery.com)
---

Qovery can create a Preview Environment for this PR.
To trigger its creation, please post a comment with one of the following command.

| Command | Blueprint environment |
|---|---|
| /qovery []() preview cc1de7de-94e5-40f8-8e45-bc8986d9dfec | [storybook](https://console.qovery.com/organization/3d542888-3d2c-474a-b1ad-712556db66da/project/a64f6cc1-4e34-433b-b8fd-5359716fb01b/environment/cc1de7de-94e5-40f8-8e45-bc8986d9dfec/services/general) |
 /qovery []() preview 28c47145-c8e7-4b9d-8d9e-c65c95b48425 | [staging](https://console.qovery.com/organization/3d542888-3d2c-474a-b1ad-712556db66da/project/a64f6cc1-4e34-433b-b8fd-5359716fb01b/environment/28c47145-c8e7-4b9d-8d9e-c65c95b48425/services/general) |
| /qovery []() preview {all\|UUID1,UUID2,...} | To preview multiple environments |

---

This comment has been generated from [Qovery](https://qovery.com) AI :robot:.
Below, a word from its wisdom :
> You are going to thank you later if it contains tests

2024-03-07 13:57 UTC, RemiBonnet requested changes
I added two feedback on comment + I don't know if it's relative to the migration but during my tests I see this problem: https://www.loom.com/share/129667bbcecf484c99957f3a408e5535

2024-03-07 13:57 UTC, RemiBonnet commented on libs/domains/environments/data-access/src/lib/domains-environments-data-access.ts
> +  details: (environmentId: string) => ({
```suggestion
  details: ({ environmentId }: { environmentId: string }) => ({
```

2024-03-07 13:57 UTC, RemiBonnet commented on libs/domains/environments/feature/src/lib/hooks/use-environment/use-environment.ts
> +    ...queries.environments.details(environmentId!!),
```suggestion
    ...queries.environments.details({ environmentId: environmentId!! }),
```

2024-03-08 16:10 UTC, ctjhoa commented on libs/domains/environments/data-access/src/lib/domains-environments-data-access.ts
> +  details: (environmentId: string) => ({
https://github.com/Qovery/console/pull/1233/commits/863b9d76cb88f8e4cc961e8bac9ed2eacd081200

2024-03-08 16:22 UTC, RemiBonnet approved these changes

2024-03-08 16:24 UTC, merged