feat(git-token): add services count
Qovery/console pull request #1234
Opened 2024-03-07 11:20 UTC by RemiBonnet

# What does this PR do?

https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-896

<img width="726" alt="Capture d’écran 2024-03-07 à 12 19 39" src="https://github.com/Qovery/console/assets/533928/d48f88c8-1272-445a-8e0e-da9d046890c6">

<img width="956" alt="Capture d’écran 2024-03-15 à 15 55 06" src="https://github.com/Qovery/console/assets/533928/b39341f0-8a41-41f4-bf43-cccfb2246053">

<img width="1394" alt="Capture d’écran 2024-03-15 à 15 56 23" src="https://github.com/Qovery/console/assets/533928/8a4a0f33-db34-4800-aa82-92e5405cc1df">

---

## PR Checklist

- [ ] This PR introduces breaking change(s) and has been labeled as such
- [ ] This PR introduces new store changes
- [ ] I have followed the library pattern i.e `feature`, `ui`, `data`, `utils`
- [x] I made sure the code is type safe (no any)

2024-03-07 11:20 UTC, RemiBonnet commented
[![Qovery Preview](https://www.qovery.com/images/logo-white.svg)](https://www.qovery.com)
---

Qovery can create a Preview Environment for this PR.
To trigger its creation, please post a comment with one of the following command.

| Command | Blueprint environment |
|---|---|
| /qovery []() preview cc1de7de-94e5-40f8-8e45-bc8986d9dfec | [storybook](https://console.qovery.com/organization/3d542888-3d2c-474a-b1ad-712556db66da/project/a64f6cc1-4e34-433b-b8fd-5359716fb01b/environment/cc1de7de-94e5-40f8-8e45-bc8986d9dfec/services/general) |
 /qovery []() preview 28c47145-c8e7-4b9d-8d9e-c65c95b48425 | [staging](https://console.qovery.com/organization/3d542888-3d2c-474a-b1ad-712556db66da/project/a64f6cc1-4e34-433b-b8fd-5359716fb01b/environment/28c47145-c8e7-4b9d-8d9e-c65c95b48425/services/general) |
| /qovery []() preview {all\|UUID1,UUID2,...} | To preview multiple environments |

---

This comment has been generated from [Qovery](https://qovery.com) AI :robot:.
Below, a word from its wisdom :
> The backlog never ends, be at peace with it

2024-03-07 11:22 UTC, RemiBonnet commented on libs/shared/ui/src/lib/components/accordion/accordion.tsx
>        className={twMerge(
I removed the children wrapper to allow the possibility to override every class name

2024-03-15 16:26 UTC, ctjhoa requested changes

2024-03-15 16:26 UTC, ctjhoa commented on libs/domains/organizations/feature/src/lib/git-token-list/git-token-list.spec.tsx
> +// Importez toutes les fonctions du module
to remove / translation

2024-03-15 17:16 UTC, ctjhoa approved these changes

2024-03-15 17:25 UTC, merged

2024-03-18 13:19 UTC, RemiBonnet commented
:tada: This PR is included in version 1.104.0 :tada:

The release is available on [GitHub release](https://github.com/Qovery/console/releases/tag/v1.104.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: