feat(annotations-settings): add feature
Qovery/console pull request #1268
Opened 2024-04-09 10:50 UTC by RemiBonnet

# What does this PR do?

https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-1055

<img width="1544" alt="Screenshot 2024-04-09 at 12 50 02" src="https://github.com/Qovery/console/assets/533928/0fc14323-7c3e-416a-bd13-c3515b44314f">

---

## PR Checklist

- [ ] This PR introduces breaking change(s) and has been labeled as such
- [ ] This PR introduces new store changes
- [ ] I have followed the library pattern i.e `feature`, `ui`, `data`, `utils`
- [x] I made sure the code is type safe (no any)

2024-04-09 10:50 UTC, RemiBonnet commented
[![Qovery Preview](https://www.qovery.com/images/logo-white.svg)](https://www.qovery.com)
---

Qovery can create a Preview Environment for this PR.
To trigger its creation, please post a comment with one of the following command.

| Command | Blueprint environment |
|---|---|
| /qovery []() preview cc1de7de-94e5-40f8-8e45-bc8986d9dfec | [storybook](https://console.qovery.com/organization/3d542888-3d2c-474a-b1ad-712556db66da/project/a64f6cc1-4e34-433b-b8fd-5359716fb01b/environment/cc1de7de-94e5-40f8-8e45-bc8986d9dfec/services/general) |
 /qovery []() preview 28c47145-c8e7-4b9d-8d9e-c65c95b48425 | [staging](https://console.qovery.com/organization/3d542888-3d2c-474a-b1ad-712556db66da/project/a64f6cc1-4e34-433b-b8fd-5359716fb01b/environment/28c47145-c8e7-4b9d-8d9e-c65c95b48425/services/general) |
| /qovery []() preview {all\|UUID1,UUID2,...} | To preview multiple environments |

---

This comment has been generated from [Qovery](https://qovery.com) AI :robot:.
Below, a word from its wisdom :
> Help yourself at 2AM by putting some metrics to help observability

2024-04-09 10:50 UTC, RemiBonnet commented
/qovery preview 28c47145-c8e7-4b9d-8d9e-c65c95b48425

2024-04-09 10:54 UTC, RemiBonnet commented on libs/shared/ui/src/lib/components/status-chip/status-chip.tsx
> +      'WAITING_STOPPING',
API doc requirements

2024-04-09 13:15 UTC, ctjhoa requested changes

2024-04-09 13:15 UTC, ctjhoa commented on libs/shared/ui/src/lib/components/navigation-left/navigation-left.tsx
> +  iconName?: IconName
Add mutual exclusion between `icon` and `iconName` using something like:
```ts
type NavigationLeftLinkProps = {
  // other props
} & (
  | {
      iconName: IconName
    }
  | {
      icon: string
    }
)

```

2024-04-09 13:28 UTC, RemiBonnet commented on libs/domains/organizations/feature/src/index.ts
> +export * from './lib/hooks/use-edit-annotations-group/use-edit-annotations-group'
https://github.com/Qovery/console/pull/1268/commits/58262bf710bf75a4c69be9c17ee33a27353f281e

2024-04-09 16:23 UTC, ctjhoa approved these changes

2024-04-11 13:40 UTC, merged

2024-04-15 08:04 UTC, RemiBonnet commented
:tada: This PR is included in version 1.111.0 :tada:

The release is available on [GitHub release](https://github.com/Qovery/console/releases/tag/v1.111.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: