feat(404): init for project environments and services
Qovery/console pull request #1338
Opened 2024-05-03 16:37 UTC by RemiBonnet

# What does this PR do?

> Link to the JIRA ticket

Put description here

> Screenshot of the feature

---

## PR Checklist

- [ ] This PR introduces breaking change(s) and has been labeled as such
- [ ] This PR introduces new store changes
- [ ] I have followed the library pattern i.e `feature`, `ui`, `data`, `utils`
- [ ] I made sure the code is type safe (no any)

2024-05-03 16:37 UTC, RemiBonnet commented
[![Qovery Preview](https://www.qovery.com/images/logo-white.svg)](https://www.qovery.com)
---

Qovery can create a Preview Environment for this PR.
To trigger its creation, please post a comment with one of the following command.

| Command | Blueprint environment |
|---|---|
| /qovery []() preview cc1de7de-94e5-40f8-8e45-bc8986d9dfec | [storybook](https://console.qovery.com/organization/3d542888-3d2c-474a-b1ad-712556db66da/project/a64f6cc1-4e34-433b-b8fd-5359716fb01b/environment/cc1de7de-94e5-40f8-8e45-bc8986d9dfec/services/general) |
 /qovery []() preview 28c47145-c8e7-4b9d-8d9e-c65c95b48425 | [staging](https://console.qovery.com/organization/3d542888-3d2c-474a-b1ad-712556db66da/project/a64f6cc1-4e34-433b-b8fd-5359716fb01b/environment/28c47145-c8e7-4b9d-8d9e-c65c95b48425/services/general) |
| /qovery []() preview {all\|UUID1,UUID2,...} | To preview multiple environments |

---

This comment has been generated from [Qovery](https://qovery.com) AI :robot:.
Below, a word from its wisdom :
> Programs must be written for people to read, and only incidentally for machines to execute

2024-05-23 15:41 UTC, RemiBonnet commented on libs/domains/environments/feature/src/lib/hooks/use-environments/use-environments.ts
> +    error: error as Error,
Necessary to get the correct type on the components side

2024-05-23 15:41 UTC, RemiBonnet commented on libs/domains/projects/feature/src/lib/hooks/use-projects/use-projects.ts
> +    retry: 3,
After 3 retry, we need to find an error to display 404

2024-05-24 12:58 UTC, ctjhoa requested changes

2024-05-24 12:58 UTC, ctjhoa commented on apps/console/src/app/router/main.router.tsx
> +import { NotFoundPage } from '@qovery/pages/layout'
To remove

2024-05-24 12:58 UTC, ctjhoa commented on libs/pages/application/src/lib/page-application.tsx
> +  if (environmentError || (!serviceType && isSuccessServiceType)) {
```suggestion
 // serviceType can be `undefined` if the `find` method in `select` return nothing. However the query itself is still success.
 // Don't seems to have a better way for this case in react-query for now
 // https://github.com/TanStack/query/issues/1540
 // https://github.com/TanStack/query/issues/5878
  if (environmentError || (!serviceType && isSuccessServiceType)) {
```

2024-05-24 12:58 UTC, ctjhoa commented on libs/pages/application/src/lib/ui/container/container.tsx
> +export const ApplicationContext = createContext<{
To remove

2024-05-24 12:58 UTC, ctjhoa commented on libs/pages/cluster/src/lib/page-cluster.tsx
> +  if (!cluster && isFetched) {
prefer `isSuccess` + comment

2024-05-24 12:58 UTC, ctjhoa commented on libs/pages/cluster/src/lib/page-cluster.tsx
> +    return null
to remove

2024-05-28 08:03 UTC, ctjhoa approved these changes

2024-05-28 08:04 UTC, merged

2024-05-29 08:33 UTC, RemiBonnet commented
:tada: This PR is included in version 1.126.0 :tada:

The release is available on [GitHub release](https://github.com/Qovery/console/releases/tag/v1.126.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: