chore: add missing codecov token
Qovery/console pull request #1429
Opened 2024-06-17 14:10 UTC by RemiBonnet

# What does this PR do?

> Link to the JIRA ticket

Put description here

> Screenshot of the feature

---

## PR Checklist

- [ ] This PR introduces breaking change(s) and has been labeled as such
- [ ] This PR introduces new store changes
- [ ] I have followed the library pattern i.e `feature`, `ui`, `data`, `utils`
- [ ] I made sure the code is type safe (no any)

2024-06-17 14:10 UTC, RemiBonnet commented
[![Qovery Preview](https://www.qovery.com/images/logo-white.svg)](https://www.qovery.com)
---

Qovery can create a Preview Environment for this PR.
To trigger its creation, please post a comment with one of the following command.

| Command | Blueprint environment |
|---|---|
| /qovery []() preview cc1de7de-94e5-40f8-8e45-bc8986d9dfec | [storybook](https://console.qovery.com/organization/3d542888-3d2c-474a-b1ad-712556db66da/project/a64f6cc1-4e34-433b-b8fd-5359716fb01b/environment/cc1de7de-94e5-40f8-8e45-bc8986d9dfec/services/general) |
 /qovery []() preview 28c47145-c8e7-4b9d-8d9e-c65c95b48425 | [staging](https://console.qovery.com/organization/3d542888-3d2c-474a-b1ad-712556db66da/project/a64f6cc1-4e34-433b-b8fd-5359716fb01b/environment/28c47145-c8e7-4b9d-8d9e-c65c95b48425/services/general) |
| /qovery []() preview {all\|UUID1,UUID2,...} | To preview multiple environments |

---

This comment has been generated from [Qovery](https://qovery.com) AI :robot:.
Below, a word from its wisdom :
> There is no better time than now, better future does not exist

2024-06-17 14:10 UTC, RemiBonnet commented
[![Qovery Preview](https://www.qovery.com/images/logo-white.svg)](https://www.qovery.com)
---

A preview environment was automatically created via Qovery.
Click on the link below to follow its deployment and use it.
:point_right: [\[PR\] test-remi2 - chore: add missing codecov token - 2024-06-17T14:10:47Z](https://console.qovery.com/organization/3d542888-3d2c-474a-b1ad-712556db66da/project/e773b890-e6b2-4406-93a9-71f9a7ab6d73/environment/2322d3e8-e336-49a7-9fdc-e4a6cb9b288a/services/general)

 Another comment will be posted when deployments are finished

2024-06-17 14:15 UTC, RemiBonnet commented
[![Qovery Preview](https://www.qovery.com/images/logo-white.svg)](https://www.qovery.com)
---

Your preview environment failed to be deployed !
Click on the link below to check the deployment logs.
:point_right: [\[PR\] test-remi2 - chore: add missing codecov token - 2024-06-17T14:10:47Z](https://console.qovery.com/organization/3d542888-3d2c-474a-b1ad-712556db66da/project/e773b890-e6b2-4406-93a9-71f9a7ab6d73/environment/2322d3e8-e336-49a7-9fdc-e4a6cb9b288a/logs)

2024-06-18 07:53 UTC, ctjhoa requested changes

2024-06-18 07:53 UTC, ctjhoa commented on .github/workflows/test-build-and-deploy.yml
> +      - uses: codecov/codecov-action@v4.0.1
```suggestion
      - uses: codecov/codecov-action@v4
```
Github recommends using major version for actions

2024-06-18 08:04 UTC, merged

2024-06-18 12:04 UTC, RemiBonnet commented
:tada: This PR is included in version 1.133.0 :tada:

The release is available on [GitHub release](https://github.com/Qovery/console/releases/tag/v1.133.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: