feat(services): add service avatar customization
Qovery/console pull request #1527
Opened 2024-07-29 17:25 UTC by ctjhoa

# What does this PR do?

https://qovery.atlassian.net/browse/FRT-1171

2024-07-29 17:25 UTC, RemiBonnet commented
[![Qovery Preview](https://www.qovery.com/images/logo-white.svg)](https://www.qovery.com)
---

Qovery can create a Preview Environment for this PR.
To trigger its creation, please post a comment with one of the following command.

| Command | Blueprint environment |
|---|---|
| /qovery []() preview cc1de7de-94e5-40f8-8e45-bc8986d9dfec | [storybook](https://console.qovery.com/organization/3d542888-3d2c-474a-b1ad-712556db66da/project/a64f6cc1-4e34-433b-b8fd-5359716fb01b/environment/cc1de7de-94e5-40f8-8e45-bc8986d9dfec/services/general) |
 /qovery []() preview 28c47145-c8e7-4b9d-8d9e-c65c95b48425 | [staging](https://console.qovery.com/organization/3d542888-3d2c-474a-b1ad-712556db66da/project/a64f6cc1-4e34-433b-b8fd-5359716fb01b/environment/28c47145-c8e7-4b9d-8d9e-c65c95b48425/services/general) |
| /qovery []() preview {all\|UUID1,UUID2,...} | To preview multiple environments |

---

This comment has been generated from [Qovery](https://qovery.com) AI :robot:.
Below, a word from its wisdom :
> Don’t Sacrifice Readability, you are going to debug it in 6 months

2024-08-01 07:51 UTC, ctjhoa commented
/qovery preview 28c47145-c8e7-4b9d-8d9e-c65c95b48425

2024-08-01 07:51 UTC, RemiBonnet commented
[![Qovery Preview](https://www.qovery.com/images/logo-white.svg)](https://www.qovery.com)
---

A preview environment was automatically created via Qovery.
Click on the link below to follow its deployment and use it.
:point_right: [\[PR\] staging - feat(services): add service avatar customization - 2024-08-01T07:51:34Z](https://console.qovery.com/organization/3d542888-3d2c-474a-b1ad-712556db66da/project/a64f6cc1-4e34-433b-b8fd-5359716fb01b/environment/ff2ff8d1-1578-4777-898f-8c1db3c3365c/services/general)

 Another comment will be posted when deployments are finished

2024-08-01 08:01 UTC, RemiBonnet commented
[![Qovery Preview](https://www.qovery.com/images/logo-white.svg)](https://www.qovery.com)
---

Your preview environment has been successfully deployed !
Click on the link below to open your service:
:point_right: [console](https://1527-console-staging.zc531a994.rustrocks.cloud)

2024-08-02 09:58 UTC, RemiBonnet requested changes
Thanks @ctjhoa, working well!

I don't know if it's a good idea to keep other "standard" icons. For example,  if we have a `DATABASE` it's weird to have the possibility to add `APPLICATION` icon, no? 
<img width="543" alt="Screenshot 2024-08-02 at 11 55 17" src="https://github.com/user-attachments/assets/d288fbfc-f40c-4758-8f39-7510c6245786">

2024-08-02 09:58 UTC, RemiBonnet commented on libs/pages/services/src/lib/ui/page-application-create/step-general/step-general.tsx
> +import { match } from 'ts-pattern'
useless

2024-08-02 09:58 UTC, RemiBonnet commented on libs/pages/services/src/lib/ui/page-application-create/step-general/step-general.tsx
> +import { type Application, type Container } from '@qovery/domains/services/data-access'
useless as well

2024-08-02 12:30 UTC, ctjhoa commented on libs/pages/services/src/lib/ui/page-application-create/step-general/step-general.tsx
> +import { type Application, type Container } from '@qovery/domains/services/data-access'
Fixed https://github.com/Qovery/console/pull/1527/commits/935b997887e8833255fc32c2a1ad056e503f213b

2024-08-02 12:30 UTC, ctjhoa commented on libs/pages/services/src/lib/ui/page-application-create/step-general/step-general.tsx
> +import { match } from 'ts-pattern'
Fixed https://github.com/Qovery/console/pull/1527/commits/935b997887e8833255fc32c2a1ad056e503f213b

2024-08-02 12:36 UTC, ctjhoa commented on libs/domains/services/feature/src/lib/service-avatar-switcher/service-avatar-switcher.tsx
> +          if (uri === 'app://qovery-console/container') {
This is a "disguised" enum.
Backend team wanted to have a URI format to anticipate custom icon in the future.
However, this is a special type of URI https://en.wikipedia.org/wiki/List_of_URI_schemes#Unofficial_but_common_URI_schemes where `qovery-console` doesn't represent an internet domain but rather an application name.
Then we use this pattern to have an enum like icon list and we are still in control of available icons.
So the environment as nothing to do with that URI.

2024-08-02 13:14 UTC, ctjhoa commented
> Thanks @ctjhoa, working well!
> 
> I don't know if it's a good idea to keep other "standard" icons. For example, if we have a `DATABASE` it's weird to have the possibility to add `APPLICATION` icon, no? <img alt="Screenshot 2024-08-02 at 11 55 17" width="543" src="https://private-user-images.githubusercontent.com/533928/354554994-d288fbfc-f40c-4758-8f39-7510c6245786.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI2MDMzMDEsIm5iZiI6MTcyMjYwMzAwMSwicGF0aCI6Ii81MzM5MjgvMzU0NTU0OTk0LWQyODhmYmZjLWY0MGMtNDc1OC04ZjM5LTc1MTBjNjI0NTc4Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwMlQxMjUwMDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNmQ0NWExOGNlYjQ1NGMyM2ZkYTAyN2MwNzcwZTU1NDM3N2ZhOTBhMWU1NGY1MDY2NGZhM2YxMjNjNDYyYjZjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.FnLfxd4VFyVubMa4qq50B1-pX2KJVXVOIa_2GgqyJqY">

I ask Alessandro about it, he says that it could be useful in some rare case and advice to keep it that way.

2024-08-02 13:24 UTC, RemiBonnet approved these changes

2024-08-02 13:30 UTC, merged

2024-08-06 12:44 UTC, RemiBonnet commented
:tada: This PR is included in version 1.144.0 :tada:

The release is available on [GitHub release](https://github.com/Qovery/console/releases/tag/v1.144.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: