chore: update README content
Qovery/console pull request #1618
Opened 2024-08-30 13:29 UTC by RemiBonnet

# What does this PR do?

- Update some outdate paragraphes with correct content

---

## PR Checklist

- [ ] This PR introduces breaking change(s) and has been labeled as such
- [ ] This PR introduces new store changes
- [ ] I have followed the library pattern i.e `feature`, `ui`, `data`, `utils`
- [x] I made sure the code is type safe (no any)

2024-08-30 13:29 UTC, RemiBonnet commented
[![Qovery Preview](https://www.qovery.com/images/logo-white.svg)](https://www.qovery.com)
---

Qovery can create a Preview Environment for this PR.
To trigger its creation, please post a comment with one of the following command.

| Command | Blueprint environment |
|---|---|
| /qovery []() preview cc1de7de-94e5-40f8-8e45-bc8986d9dfec | [storybook](https://console.qovery.com/organization/3d542888-3d2c-474a-b1ad-712556db66da/project/a64f6cc1-4e34-433b-b8fd-5359716fb01b/environment/cc1de7de-94e5-40f8-8e45-bc8986d9dfec/services/general) |
 /qovery []() preview 28c47145-c8e7-4b9d-8d9e-c65c95b48425 | [staging](https://console.qovery.com/organization/3d542888-3d2c-474a-b1ad-712556db66da/project/a64f6cc1-4e34-433b-b8fd-5359716fb01b/environment/28c47145-c8e7-4b9d-8d9e-c65c95b48425/services/general) |
| /qovery []() preview {all\|UUID1,UUID2,...} | To preview multiple environments |

---

This comment has been generated from [Qovery](https://qovery.com) AI :robot:.
Below, a word from its wisdom :
> Help yourself at 2AM by putting some metrics to help observability

2024-09-02 14:30 UTC, ctjhoa requested changes

2024-09-02 14:30 UTC, ctjhoa commented on README.md
>  ### Why do we use NX?
```suggestion
### Why do we use Nx?
```

2024-09-02 14:30 UTC, ctjhoa commented on README.md
> +Qovery Console is in its early stage of development and we need some help, you are welcome to contribute! You can propose improvements directly from the [issues](https://github.com/Qovery/console/iss
```suggestion
Qovery Console is actively develop and we need some help, you are welcome to contribute! You can propose improvements directly from the [issues](https://github.com/Qovery/console/issues) page or include them in your pull request for changes.
```

2024-09-02 14:45 UTC, ctjhoa approved these changes

2024-09-02 14:52 UTC, merged

2024-09-03 12:46 UTC, RemiBonnet commented
:tada: This PR is included in version 1.151.1 :tada:

The release is available on [GitHub release](https://github.com/Qovery/console/releases/tag/v1.151.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: