feat(service-logs): new design
Qovery/console pull request #1661
Opened 2024-09-10 16:57 UTC by RemiBonnet

# What does this PR do?

> Link to the JIRA ticket

Put description here

> Screenshot of the feature

---

## PR Checklist

- [ ] This PR introduces breaking change(s) and has been labeled as such
- [ ] This PR introduces new store changes
- [ ] I made sure the code is type safe (no any)

2024-09-10 16:57 UTC, RemiBonnet commented
[![Qovery Preview](https://www.qovery.com/images/logo-white.svg)](https://www.qovery.com)
---

Qovery can create a Preview Environment for this PR.
To trigger its creation, please post a comment with one of the following command.

| Command | Blueprint environment |
|---|---|
| /qovery []() preview cc1de7de-94e5-40f8-8e45-bc8986d9dfec | [storybook](https://console.qovery.com/organization/3d542888-3d2c-474a-b1ad-712556db66da/project/a64f6cc1-4e34-433b-b8fd-5359716fb01b/environment/cc1de7de-94e5-40f8-8e45-bc8986d9dfec/services/general) |
 /qovery []() preview 28c47145-c8e7-4b9d-8d9e-c65c95b48425 | [staging](https://console.qovery.com/organization/3d542888-3d2c-474a-b1ad-712556db66da/project/a64f6cc1-4e34-433b-b8fd-5359716fb01b/environment/28c47145-c8e7-4b9d-8d9e-c65c95b48425/services/general) |
| /qovery []() preview {all\|UUID1,UUID2,...} | To preview multiple environments |

---

This comment has been generated from [Qovery](https://qovery.com) AI :robot:.
Below, a word from its wisdom :
> Write comments that add new information that doesn’t exist in the code

2024-09-12 08:02 UTC, fabienfleureau commented
@CodiumAI-Agent /review

2024-09-12 08:03 UTC, CodiumAI-Agent commented
## PR Reviewer Guide 🔍

<table>
<tr><td>⏱️&nbsp;<strong>Estimated effort to review</strong>: 4 🔵🔵🔵🔵⚪</td></tr>
<tr><td>🧪&nbsp;<strong>PR contains tests</strong></td></tr>
<tr><td>🔒&nbsp;<strong>No security concerns identified</strong></td></tr>
<tr><td>⚡&nbsp;<strong>Key issues to review</strong><br><br>

<a href='https://github.com/Qovery/console/pull/1661/files#diff-7dd4c7adbc90ee756eb6a3b480905e406e98cd7bb56de4669f1c0709b66ce2e8R49-R123'><strong>Performance Concern</strong></a><br>The use of `useMemo` and `useCallback` with dependencies that could frequently change might lead to performance issues. Specifically, the `now` variable in `useMemo` for `data` calculation is updated on every render, potentially leading to excessive recalculations.

<a href='https://github.com/Qovery/console/pull/1661/files#diff-7dd4c7adbc90ee756eb6a3b480905e406e98cd7bb56de4669f1c0709b66ce2e8R24-R143'><strong>Code Complexity</strong></a><br>The `useServiceLogs` hook is quite complex and handles multiple states and side effects. Consider refactoring into smaller, more manageable hooks or utilizing a state management library to improve readability and maintainability.

<a href='https://github.com/Qovery/console/pull/1661/files#diff-8b2d578ea313ec7799ba3a8a680c2139a70a15b4da09e7c86c2c08951b5995d8R82-R91'><strong>Accessibility Concern</strong></a><br>Ensure that interactive elements like buttons have appropriate ARIA labels or roles for better accessibility.

</td></tr>
</table>

2024-09-16 09:07 UTC, CodiumAI-Agent commented
**[Persistent review](https://github.com/Qovery/console/pull/1661#issuecomment-2345544850)** updated to latest commit https://github.com/Qovery/console/commit/7dd669ea6335754dd0afe2b5beb045c614a5cc41

2024-09-16 11:36 UTC, RemiBonnet commented
@CodiumAI-Agent /review

2024-09-16 11:37 UTC, CodiumAI-Agent commented
**[Persistent review](https://github.com/Qovery/console/pull/1661#issuecomment-2345544850)** updated to latest commit https://github.com/Qovery/console/commit/7dd669ea6335754dd0afe2b5beb045c614a5cc41

2024-09-17 13:17 UTC, ctjhoa requested changes

2024-09-17 13:52 UTC, RemiBonnet commented on libs/domains/service-logs/feature/src/lib/list-service-logs/list-service-logs.tsx
> +      ? [
https://github.com/Qovery/console/pull/1661

2024-09-17 13:54 UTC, RemiBonnet commented on libs/domains/service-logs/feature/src/lib/hooks/use-service-logs/use-service-logs.tsx
https://github.com/Qovery/console/commit/ee53d18341a500af9aa6cda6a4afd39f7f1f3f7c

2024-09-17 13:55 UTC, RemiBonnet commented on libs/domains/service-logs/feature/src/lib/hooks/use-service-logs/use-service-logs.tsx
> +    isLoading: false,
It's an oversight, I removed it

2024-09-17 15:18 UTC, ctjhoa approved these changes

2024-09-18 08:12 UTC, merged

2024-09-18 08:13 UTC, CodiumAI-Agent commented
**[Persistent review](https://github.com/Qovery/console/pull/1661#issuecomment-2345544850)** updated to latest commit https://github.com/Qovery/console/commit/b45b017fa2ca68215cf085d42bf6812c038f06f6

2024-09-18 13:17 UTC, CodiumAI-Agent commented
**[Persistent review](https://github.com/Qovery/console/pull/1661#issuecomment-2345544850)** updated to latest commit https://github.com/Qovery/console/commit/b45b017fa2ca68215cf085d42bf6812c038f06f6