Fix / Deployments pulling on status update
Qovery/console pull request #171
Opened 2022-06-23 11:53 UTC by WilliamTraoreee

# What does this PR do?

- Fix deployments refresh when action is launch on environment
- Change progress icon

---

## PR Checklist

### Global

- [x] This PR does not introduce any breaking change
- [ ] This PR introduces breaking change(s) and has been labeled as such
- [x] I have found someone to review this PR and pinged him

### Store

- [ ] This PR introduces new store changes

### NX

- [x] I have run the dep-graph locally and made sure the tree was clean i.e no circular dependencies
- [x] I have followed the library pattern i.e `feature`, `ui`, `data`, `utils`

### Clean Code

- [x] I made sure the code is type safe (no any)
- [ ] I have included a feature flag on my feature, if applicable

2022-06-23 11:53 UTC, evoxmusic commented
A preview environment was automatically created via Qovery.  
Click on the link below to follow its deployment and use it.  
:point_right: [[PR] staging - Fix / Deployments pulling on status update - 2022-06-23T11:53:26Z](https://console.qovery.com/platform/organization/141c07c8-0dd9-4623-983b-3fdd61867255/projects/977bd069-20f7-4b24-bd95-28b44174cf43/environments/e37acf61-a0d2-43e8-9c23-1188b0f9a1bb/applications)

2022-06-24 15:15 UTC, RemiBonnet requested changes
Hey @WilliamTraoreee, thanks !

I think all fetch (outside the status) need an condition because here you fetch element, that we don't need on the page

2022-06-24 15:15 UTC, RemiBonnet commented on libs/pages/services/src/lib/feature/page-deployments-feature/page-deployments-feature.tsx
> +      2500
Why we use `2500` for this and not `3000` ?

2022-06-27 10:06 UTC, merged

2022-11-17 10:30 UTC, bdebon commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/Qovery/console/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: