Add redirect on the previous project
Qovery/console pull request #194
Opened 2022-06-28 12:59 UTC by WilliamTraoreee

# What does this PR do?

Store the current organizationId and projectId on the localStorage to redirect the user on it on the next session/login

---

## PR Checklist

### Global

- [x] This PR does not introduce any breaking change
- [ ] This PR introduces breaking change(s) and has been labeled as such
- [x] I have found someone to review this PR and pinged him

### Store

- [x] This PR introduces new store changes

### NX

- [x] I have run the dep-graph locally and made sure the tree was clean i.e no circular dependencies
- [x] I have followed the library pattern i.e `feature`, `ui`, `data`, `utils`

### Clean Code

- [x] I made sure the code is type safe (no any)
- [ ] I have included a feature flag on my feature, if applicable

2022-06-29 07:39 UTC, bdebon requested changes

2022-06-29 07:39 UTC, bdebon commented on libs/pages/login/src/lib/hooks/use-redirect-if-logged/use-redirect-if-logged.tsx
> +      if (redirectLoginUri) {
Could be very nice to add some testing for these two conditions! 
Like if redirectLoginUri is set, you call well the navigate function. You make sure that the navigate function is called. 
With that no one can remove this redirection without the test failing. It's a good safe keeper. Good opportunity to play with Wallaby also and make sure that you go in every function

2022-06-29 07:39 UTC, bdebon commented on libs/shared/router/src/lib/protected-route/protected-route.tsx
> +    localStorage.setItem('redirectLoginUri', location.pathname)
Same asserting that we are well setting the item in the local storage when an user is not authenticated could be a nice non regression test.

2022-06-30 12:18 UTC, RemiBonnet approved these changes

2022-06-30 12:21 UTC, merged