feat(infra-logs): remove internal links
Qovery/console pull request #208
Opened 2022-07-04 09:59 UTC by RemiBonnet

# What does this PR do?

- Infra logs page, remove the internal redirect
- Activate beta route

---

## PR Checklist

### Global

- [x] This PR does not introduce any breaking change
- [ ] This PR introduces breaking change(s) and has been labeled as such
- [x] I have found someone to review this PR and pinged him

### Store

- [ ] This PR introduces new store changes

### NX

- [x] I have run the dep-graph locally and made sure the tree was clean i.e no circular dependencies
- [x] I have followed the library pattern i.e `feature`, `ui`, `data`, `utils`

### Clean Code

- [x] I made sure the code is type safe (no any)
- [x] I have included a feature flag on my feature, if applicable

2022-07-04 09:59 UTC, evoxmusic commented
A preview environment was automatically created via Qovery.  
Click on the link below to follow its deployment and use it.  
:point_right: [[PR] staging - feat(infra-logs): remove internal links - 2022-07-04T09:59:57Z](https://console.qovery.com/platform/organization/141c07c8-0dd9-4623-983b-3fdd61867255/projects/977bd069-20f7-4b24-bd95-28b44174cf43/environments/6deedebe-041e-4ea2-a2b4-a477c531e314/applications)

2022-07-04 10:03 UTC, bdebon requested changes

2022-07-04 10:03 UTC, bdebon commented on libs/pages/layout/src/lib/ui/navigation/navigation.tsx
> +  const matchLogInfraRoute = matchPath(pathname, INFRA_LOGS_URL(organizationId, clusterId))
Can we factorize both matchLogInfraRoute in a util so that we use always the same one and so that we can test the result of the function?

2022-07-04 10:04 UTC, bdebon requested changes

2022-07-04 10:04 UTC, bdebon commented on libs/shared/ui/src/lib/components/layouts/breadcrumb/breadcrumb.tsx
> +  const matchLogInfraRoute = matchPath(location.pathname || '', INFRA_LOGS_URL(organizationId, clusterId))
To refactor

2022-07-04 10:26 UTC, merged

2022-11-17 10:29 UTC, bdebon commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/Qovery/console/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: