feat(settings-environments): danger zone
Qovery/console pull request #237
Opened 2022-07-19 13:26 UTC by RemiBonnet

# What does this PR do?

[> Link to the JIRA ticket
](https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-385)

- Add component global delete
<img width="1723" alt="Capture d’écran 2022-07-19 à 15 25 34" src="https://user-images.githubusercontent.com/533928/179761421-c19f8eaa-98f4-46a7-af69-8c50a5eb58d5.png">

---

## PR Checklist

### Global

- [x] This PR does not introduce any breaking change
- [ ] This PR introduces breaking change(s) and has been labeled as such
- [x] I have found someone to review this PR and pinged him

### Store

- [ ] This PR introduces new store changes

### NX

- [x] I have run the dep-graph locally and made sure the tree was clean i.e no circular dependencies
- [x] I have followed the library pattern i.e `feature`, `ui`, `data`, `utils`

### Clean Code

- [x] I made sure the code is type safe (no any)
- [ ] I have included a feature flag on my feature, if applicable

2022-07-19 13:26 UTC, evoxmusic commented
A preview environment was automatically created via Qovery.  
Click on the link below to follow its deployment and use it.  
:point_right: [[PR] staging - feat(settings-environments): danger zone - 2022-07-19T13:26:08Z](https://console.qovery.com/platform/organization/141c07c8-0dd9-4623-983b-3fdd61867255/projects/977bd069-20f7-4b24-bd95-28b44174cf43/environments/4966cc64-99e3-4a84-a34b-2cf5e9ae9983/applications)

2022-07-20 08:49 UTC, bdebon requested changes
Hey Remi,
I added some comments and suggestions directly to the code.

Also I have a question that has been in my mind lately. We have many components in the shared UI lib that do not have stories. It's most of them complex component like here with this `BlockContentDelete` 
It could be cool to have stories for these more complex components so that coming devs can know that they exist and that they can use them. Maybe we can add a subchapter in storybook named something like : `Composed Components` that are components made with an assembly of smaller components.

Open to discussion

2022-07-20 08:49 UTC, bdebon commented on libs/shared/ui/src/lib/components/block-content-delete/block-content-delete.tsx
> +          <Button className="mt-3 ml-auto" onClick={callback} style={ButtonStyle.ERROR}>
There is no confirm dialog that open before doing the callback action? I thought that the confirm/popup part would be part of this component

2022-07-20 08:49 UTC, bdebon commented on libs/shared/ui/src/lib/components/block-content-delete/block-content-delete.spec.tsx
> +    )
Need to add a test that simulate the click on the button to see if the callback has been called. 
act() click spy.hasbeencalled

2022-07-20 08:49 UTC, bdebon commented on libs/shared/ui/src/lib/components/block-content-delete/block-content-delete.tsx
> +          <Button className="mt-3 ml-auto" onClick={callback} style={ButtonStyle.ERROR}>
I think for something that critical we need a confirm

2022-07-20 09:13 UTC, bdebon commented on libs/pages/services/src/lib/ui/page-settings-danger-zone/page-settings-danger-zone.tsx
> +          className="w-[580px]"
Can we put this value in the theme? 
If one day we want to increase the size of all our boxes we could in one go with the tailwind theme

2022-07-21 08:14 UTC, merged

2022-11-17 10:28 UTC, bdebon commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/Qovery/console/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: