feat(environment-logs): add deployment history
Qovery/console pull request #729
Opened 2023-08-02 16:19 UTC by RemiBonnet

# What does this PR do?

[> Link to the JIRA ticket
](https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-690)

- Add deployment history for Environment logs

---

## PR Checklist

- [ ] This PR introduces breaking change(s) and has been labeled as such
- [ ] This PR introduces new store changes
- [x] I have followed the library pattern i.e `feature`, `ui`, `data`, `utils`
- [x] I made sure the code is type safe (no any)

2023-08-04 13:02 UTC, RemiBonnet commented
/qovery preview 28c47145-c8e7-4b9d-8d9e-c65c95b48425

2023-08-04 13:03 UTC, acarranoqovery commented
[![Qovery Preview](https://www.qovery.com/images/logo-white.svg)](https://www.qovery.com)
---

A preview environment was automatically created via Qovery.
Click on the link below to follow its deployment and use it.
:point_right: [\[PR\] staging - feat(environment-logs): add deployment history - 2023-08-04T13:03:00Z](https://console.qovery.com/organization/3d542888-3d2c-474a-b1ad-712556db66da/project/a64f6cc1-4e34-433b-b8fd-5359716fb01b/environment/11b0ac74-d540-471b-83c9-d37b43681052/services/general)

 Another comment will be posted when deployments are terminated

2023-08-09 21:58 UTC, ctjhoa requested changes

2023-08-09 21:58 UTC, ctjhoa commented on libs/pages/logs/environment/src/lib/feature/deployment-logs-feature/deployment-logs-feature.tsx
> +  useWebSocket(deploymentLogsUrl, {
We should use common hook based [this hook](https://github.com/Qovery/console/pull/744)

2023-08-10 08:11 UTC, ctjhoa commented on libs/shared/ui/src/lib/components/menu/menu.tsx
> +        menuClassName={`rounded-md shadow-[0_0_32px_rgba(0,0,0,0.08)] p-0 menu__container menu__container--${direction} menu__container--${
Ok className is already applied to the parent div

2023-08-10 12:37 UTC, RemiBonnet commented on libs/shared/utils/src/lib/tools/date.tsx
> +export const dateFullFormat = (date: string, timeZone?: string, customFormat = 'dd MMM, HH:mm:ss') => {
Yep done

2023-08-10 12:45 UTC, RemiBonnet commented on libs/shared/console-shared/src/lib/layout-logs/layout-logs.tsx
> +              DEPLOYMENT_LOGS_VERSION_URL(serviceId, versionId !== ':versionId' ? '' : versionId),
Fixed, not necessary I forgot to remove this condition, thanks!

2023-08-10 14:40 UTC, ctjhoa approved these changes

2023-08-10 14:58 UTC, merged

2023-08-10 15:02 UTC, RemiBonnet commented
:tada: This PR is included in version 1.46.0 :tada:

The release is available on [GitHub release](https://github.com/Qovery/console/releases/tag/v1.46.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: