chore: codecov update target for patch/project
Qovery/console pull request #735
Opened 2023-08-04 13:00 UTC by RemiBonnet

# What does this PR do?

- Update Codecov target 

---

## PR Checklist

- [ ] This PR introduces breaking change(s) and has been labeled as such
- [ ] This PR introduces new store changes
- [x] I have followed the library pattern i.e `feature`, `ui`, `data`, `utils`
- [x] I made sure the code is type safe (no any)

2023-08-04 13:07 UTC, acarranoqovery commented
[![Qovery Preview](https://www.qovery.com/images/logo-white.svg)](https://www.qovery.com)
---

A preview environment was automatically created via Qovery.
Click on the link below to follow its deployment and use it.
:point_right: [\[PR\] staging - chore: codecov update target for patch/project - 2023-08-04T13:07:17Z](https://console.qovery.com/organization/3d542888-3d2c-474a-b1ad-712556db66da/project/a64f6cc1-4e34-433b-b8fd-5359716fb01b/environment/ac7097d7-e652-414d-8639-a0d27ee9ba8b/services/general)

 Another comment will be posted when deployments are terminated

2023-08-04 13:08 UTC, acarranoqovery commented
[![Qovery Preview](https://www.qovery.com/images/logo-white.svg)](https://www.qovery.com)
---

Your preview environment failed to be deployed !
Click on the link below to check the deployment logs.
:point_right: [\[PR\] staging - chore: codecov update target for patch/project - 2023-08-04T13:07:17Z](https://console.qovery.com/organization/3d542888-3d2c-474a-b1ad-712556db66da/project/a64f6cc1-4e34-433b-b8fd-5359716fb01b/environment/ac7097d7-e652-414d-8639-a0d27ee9ba8b/logs)

2023-08-04 14:14 UTC, ctjhoa approved these changes

2023-08-04 14:38 UTC, ctjhoa requested changes
Reading more about codecov
https://about.codecov.io/blog/the-5-levels-of-code-coverage-how-to-build-a-testing-culture-in-your-organization/

I think this is more relevant for our usage for now.

2023-08-04 14:38 UTC, ctjhoa commented on .codecov.yml
> +        target: 60%
```suggestion
        target: auto
    patch: off
```

2023-08-04 15:08 UTC, ctjhoa approved these changes

2023-08-04 15:10 UTC, merged

2023-08-07 15:49 UTC, RemiBonnet commented
:tada: This PR is included in version 1.45.0 :tada:

The release is available on [GitHub release](https://github.com/Qovery/console/releases/tag/v1.45.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: