feat(logs-placeholder): update placeholder for Logs
Qovery/console pull request #790
Opened 2023-08-28 18:24 UTC by RemiBonnet

# What does this PR do?

> Link to the JIRA ticket

Put description here

> Screenshot of the feature

---

## PR Checklist

- [ ] This PR introduces breaking change(s) and has been labeled as such
- [ ] This PR introduces new store changes
- [ ] I have followed the library pattern i.e `feature`, `ui`, `data`, `utils`
- [ ] I made sure the code is type safe (no any)

2023-08-28 18:24 UTC, acarranoqovery commented
[![Qovery Preview](https://www.qovery.com/images/logo-white.svg)](https://www.qovery.com)
---

Qovery can create a Preview Environment for this PR.
To trigger its creation, please post a comment with one of the following command.

| Command | Blueprint environment |
|---|---|
| /qovery <!-- combo breaker --> preview 937d87a0-2391-4f54-8dbb-e263f2b05c0e | [test-old-status](https://console.qovery.com/organization/3d542888-3d2c-474a-b1ad-712556db66da/project/a64f6cc1-4e34-433b-b8fd-5359716fb01b/environment/937d87a0-2391-4f54-8dbb-e263f2b05c0e/services/general) |
 /qovery <!-- combo breaker --> preview 28c47145-c8e7-4b9d-8d9e-c65c95b48425 | [staging](https://console.qovery.com/organization/3d542888-3d2c-474a-b1ad-712556db66da/project/a64f6cc1-4e34-433b-b8fd-5359716fb01b/environment/28c47145-c8e7-4b9d-8d9e-c65c95b48425/services/general) |
| /qovery <!-- combo breaker --> preview {all\|UUID1,UUID2,...} | To preview multiple environments |

---

This comment has been generated from [Qovery](https://qovery.com) AI :robot:.
Below, a word from its wisdom :
> Take rest sometimes

2023-08-29 15:12 UTC, ctjhoa requested changes

2023-08-29 15:12 UTC, ctjhoa commented on libs/shared/console-shared/src/lib/layout-logs/layout-logs.tsx
> +            (service as DatabaseEntity)?.mode === DatabaseModeEnum.MANAGED ? false : true
```suggestion
            (service as DatabaseEntity)?.mode !== DatabaseModeEnum.MANAGED
```

2023-08-29 15:16 UTC, acarranoqovery commented
[![Qovery Preview](https://www.qovery.com/images/logo-white.svg)](https://www.qovery.com)
---

Your preview environment has been successfully deployed !
Click on the link below to open your service:
:point_right: [console](https://790-console-test-old-status.zc531a994.rustrocks.cloud)

2023-08-29 15:47 UTC, ctjhoa approved these changes

2023-08-29 16:02 UTC, merged

2023-09-01 09:16 UTC, RemiBonnet commented
:tada: This PR is included in version 1.50.0 :tada:

The release is available on [GitHub release](https://github.com/Qovery/console/releases/tag/v1.50.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: