fix(layout-logs): animation progressing
Qovery/console pull request #869
Opened 2023-10-02 13:51 UTC by RemiBonnet

# What does this PR do?

https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-850

---

## PR Checklist

- [ ] This PR introduces breaking change(s) and has been labeled as such
- [ ] This PR introduces new store changes
- [x] I have followed the library pattern i.e `feature`, `ui`, `data`, `utils`
- [x] I made sure the code is type safe (no any)

2023-10-02 13:51 UTC, acarranoqovery commented
[![Qovery Preview](https://www.qovery.com/images/logo-white.svg)](https://www.qovery.com)
---

Qovery can create a Preview Environment for this PR.
To trigger its creation, please post a comment with one of the following command.

| Command | Blueprint environment |
|---|---|
| /qovery <!-- combo breaker --> preview 28c47145-c8e7-4b9d-8d9e-c65c95b48425 | [staging](https://console.qovery.com/organization/3d542888-3d2c-474a-b1ad-712556db66da/project/a64f6cc1-4e34-433b-b8fd-5359716fb01b/environment/28c47145-c8e7-4b9d-8d9e-c65c95b48425/services/general) |
| /qovery <!-- combo breaker --> preview {all\|UUID1,UUID2,...} | To preview multiple environments |

---

This comment has been generated from [Qovery](https://qovery.com) AI :robot:.
Below, a word from its wisdom :
> You are going to thank you later if it contains tests

2023-10-02 13:51 UTC, RemiBonnet commented
/qovery preview 28c47145-c8e7-4b9d-8d9e-c65c95b48425

2023-10-02 13:51 UTC, acarranoqovery commented
[![Qovery Preview](https://www.qovery.com/images/logo-white.svg)](https://www.qovery.com)
---

A preview environment was automatically created via Qovery.
Click on the link below to follow its deployment and use it.
:point_right: [\[PR\] staging - fix(layout-logs): update progressing animation - 2023-10-02T13:51:55Z](https://console.qovery.com/organization/3d542888-3d2c-474a-b1ad-712556db66da/project/a64f6cc1-4e34-433b-b8fd-5359716fb01b/environment/339ecb2f-cdfa-480d-8600-40bd59900996/services/general)

 Another comment will be posted when deployments are terminated

2023-10-02 13:57 UTC, acarranoqovery commented
[![Qovery Preview](https://www.qovery.com/images/logo-white.svg)](https://www.qovery.com)
---

Your preview environment has been successfully deployed !
Click on the link below to open your service:
:point_right: [console](https://869-console-staging.zc531a994.rustrocks.cloud)

2023-10-03 07:59 UTC, ctjhoa requested changes

2023-10-03 07:59 UTC, ctjhoa commented on libs/pages/logs/environment/src/lib/page-environment-logs.tsx
> +import { useRunningStatus } from '@qovery/domains/services/feature'
unused

2023-10-03 18:18 UTC, ctjhoa approved these changes

2023-10-04 07:17 UTC, merged

2023-10-04 08:03 UTC, RemiBonnet commented
:tada: This PR is included in version 1.56.0 :tada:

The release is available on [GitHub release](https://github.com/Qovery/console/releases/tag/v1.56.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: