feat(cluster): add deployment error banner
Qovery/console pull request #923
Opened 2023-10-26 16:04 UTC by RemiBonnet

# What does this PR do?

https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-847

You can test with this [Cluster](http://localhost:4200/organization/460616f0-94da-4d35-b631-6fa4ed08eb9a/cluster/be9e22b0-d05a-4330-b5b5-547667d380fd/settings/general). 

---

## PR Checklist

- [ ] This PR introduces breaking change(s) and has been labeled as such
- [ ] This PR introduces new store changes
- [x] I have followed the library pattern i.e `feature`, `ui`, `data`, `utils`
- [x] I made sure the code is type safe (no any)

2023-10-26 16:04 UTC, acarranoqovery commented
[![Qovery Preview](https://www.qovery.com/images/logo-white.svg)](https://www.qovery.com)
---

Qovery can create a Preview Environment for this PR.
To trigger its creation, please post a comment with one of the following command.

| Command | Blueprint environment |
|---|---|
| /qovery <!-- combo breaker --> preview 28c47145-c8e7-4b9d-8d9e-c65c95b48425 | [staging](https://console.qovery.com/organization/3d542888-3d2c-474a-b1ad-712556db66da/project/a64f6cc1-4e34-433b-b8fd-5359716fb01b/environment/28c47145-c8e7-4b9d-8d9e-c65c95b48425/services/general) |
| /qovery <!-- combo breaker --> preview {all\|UUID1,UUID2,...} | To preview multiple environments |

---

This comment has been generated from [Qovery](https://qovery.com) AI :robot:.
Below, a word from its wisdom :
> Programs must be written for people to read, and only incidentally for machines to execute

2023-10-26 16:04 UTC, RemiBonnet commented
[![Qovery Preview](https://www.qovery.com/images/logo-white.svg)](https://www.qovery.com)
---

A preview environment was automatically created via Qovery.
Click on the link below to follow its deployment and use it.
:point_right: [\[PR\] my-env - feat(cluster): add deployment error banner - 2023-10-26T16:04:36Z](https://console.qovery.com/organization/3d542888-3d2c-474a-b1ad-712556db66da/project/e773b890-e6b2-4406-93a9-71f9a7ab6d73/environment/c83b7df2-e605-4bfe-9759-754f5590d246/services/general)

 Another comment will be posted when deployments are terminated

2023-10-26 16:26 UTC, RemiBonnet commented
[![Qovery Preview](https://www.qovery.com/images/logo-white.svg)](https://www.qovery.com)
---

Your preview environment failed to be deployed !
Click on the link below to check the deployment logs.
:point_right: [\[PR\] my-env - feat(cluster): add deployment error banner - 2023-10-26T16:04:36Z](https://console.qovery.com/organization/3d542888-3d2c-474a-b1ad-712556db66da/project/e773b890-e6b2-4406-93a9-71f9a7ab6d73/environment/c83b7df2-e605-4bfe-9759-754f5590d246/logs)

2023-10-27 14:12 UTC, ctjhoa requested changes

2023-10-27 18:37 UTC, RemiBonnet commented on libs/pages/layout/src/lib/ui/layout-page/layout-page.tsx
> +  const clustersDeploymentError = clusters?.filter((c) => c.status === ClusterStateEnum.DEPLOYMENT_ERROR)
https://github.com/Qovery/console/pull/923/commits/e345d07c1f873a9021a0c9246c370ae92e6cf5c3

2023-10-30 09:30 UTC, ctjhoa approved these changes

2023-10-30 10:12 UTC, merged

2023-10-30 10:17 UTC, RemiBonnet commented
:tada: This PR is included in version 1.61.0 :tada:

The release is available on [GitHub release](https://github.com/Qovery/console/releases/tag/v1.61.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: