feat(organization): migrate billing to react query
Qovery/console pull request #954
Opened 2023-11-08 16:46 UTC by RemiBonnet

# What does this PR do?

> Link to the JIRA ticket

Put description here

> Screenshot of the feature

---

## PR Checklist

- [ ] This PR introduces breaking change(s) and has been labeled as such
- [ ] This PR introduces new store changes
- [ ] I have followed the library pattern i.e `feature`, `ui`, `data`, `utils`
- [ ] I made sure the code is type safe (no any)

2023-11-08 16:46 UTC, acarranoqovery commented
[![Qovery Preview](https://www.qovery.com/images/logo-white.svg)](https://www.qovery.com)
---

Qovery can create a Preview Environment for this PR.
To trigger its creation, please post a comment with one of the following command.

| Command | Blueprint environment |
|---|---|
| /qovery <!-- combo breaker --> preview 28c47145-c8e7-4b9d-8d9e-c65c95b48425 | [staging](https://console.qovery.com/organization/3d542888-3d2c-474a-b1ad-712556db66da/project/a64f6cc1-4e34-433b-b8fd-5359716fb01b/environment/28c47145-c8e7-4b9d-8d9e-c65c95b48425/services/general) |
| /qovery <!-- combo breaker --> preview {all\|UUID1,UUID2,...} | To preview multiple environments |

---

This comment has been generated from [Qovery](https://qovery.com) AI :robot:.
Below, a word from its wisdom :
> There is no better time than now, better future does not exist

2023-11-09 15:29 UTC, RemiBonnet commented on libs/pages/events/src/lib/ui/row-event/row-event.tsx
> +      [OrganizationEventTargetType.HELM]: () => <div />,
Fix needed with the update of api doc

2023-11-10 13:24 UTC, ctjhoa requested changes

2023-11-10 13:24 UTC, ctjhoa commented on .eslintrc.json
> +      "files": ["*.ts", "*.tsx"],
We already have a `"files": ["*.ts", "*.tsx"]` line 36

2023-11-10 13:24 UTC, ctjhoa commented on libs/pages/events/src/lib/ui/row-event/row-event.tsx
> +      [OrganizationEventTargetType.HELM]: () => <div />,
return `null` instead

2023-11-10 15:33 UTC, ctjhoa approved these changes

2023-11-10 15:36 UTC, merged

2023-11-13 09:28 UTC, RemiBonnet commented
:tada: This PR is included in version 1.64.0 :tada:

The release is available on [GitHub release](https://github.com/Qovery/console/releases/tag/v1.64.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: