feat(organization): migrate billing to react query
Qovery/console pull request #957
Opened 2023-11-10 13:22 UTC by RemiBonnet

# What does this PR do?

https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-844

---

## PR Checklist

- [ ] This PR introduces breaking change(s) and has been labeled as such
- [ ] This PR introduces new store changes
- [x] I have followed the library pattern i.e `feature`, `ui`, `data`, `utils`
- [x] I made sure the code is type safe (no any)

2023-11-10 13:22 UTC, acarranoqovery commented
[![Qovery Preview](https://www.qovery.com/images/logo-white.svg)](https://www.qovery.com)
---

Qovery can create a Preview Environment for this PR.
To trigger its creation, please post a comment with one of the following command.

| Command | Blueprint environment |
|---|---|
| /qovery <!-- combo breaker --> preview 28c47145-c8e7-4b9d-8d9e-c65c95b48425 | [staging](https://console.qovery.com/organization/3d542888-3d2c-474a-b1ad-712556db66da/project/a64f6cc1-4e34-433b-b8fd-5359716fb01b/environment/28c47145-c8e7-4b9d-8d9e-c65c95b48425/services/general) |
| /qovery <!-- combo breaker --> preview {all\|UUID1,UUID2,...} | To preview multiple environments |

---

This comment has been generated from [Qovery](https://qovery.com) AI :robot:.
Below, a word from its wisdom :
> Take rest sometimes

2023-11-15 14:49 UTC, ctjhoa requested changes

2023-11-15 14:49 UTC, ctjhoa commented on libs/domains/organizations/data-access/src/lib/domains-organizations-data-access.ts
> +  }),
```suggestion
  list: {
    queryKey: null,
    async queryFn() {
      const response = await organizationApi.listOrganization()
      return response.data.results
    },
  },
```

2023-11-15 14:49 UTC, ctjhoa commented on libs/domains/organizations/feature/src/lib/hooks/use-create-organization/use-create-organization.tsx
> +        queryKey: queries.organizations.list().queryKey,
```suggestion
        queryKey: queries.organizations.list.queryKey,
```

2023-11-15 14:49 UTC, ctjhoa commented on libs/domains/organizations/feature/src/lib/hooks/use-organization/use-organization.tsx
> +    enabled: enabled,
```suggestion
    enabled,
```

2023-11-15 14:49 UTC, ctjhoa commented on libs/pages/layout/src/lib/feature/layout/layout.tsx
> +    }
```suggestion
    const organizationIds = organizations.map(({ id }) => id)
```

2023-11-15 16:15 UTC, RemiBonnet commented on libs/pages/layout/src/lib/feature/layout/layout.tsx
> +    }
https://github.com/Qovery/console/pull/957/commits/0d149391e88d4eedad1522e4b0075b175900a98f

2023-11-15 16:15 UTC, RemiBonnet commented on libs/domains/organizations/feature/src/lib/hooks/use-organization/use-organization.tsx
> +    enabled: enabled,
https://github.com/Qovery/console/pull/957/commits/0d149391e88d4eedad1522e4b0075b175900a98f

2023-11-15 16:15 UTC, RemiBonnet commented on libs/domains/organizations/feature/src/lib/hooks/use-create-organization/use-create-organization.tsx
> +        queryKey: queries.organizations.list().queryKey,
https://github.com/Qovery/console/pull/957/commits/0d149391e88d4eedad1522e4b0075b175900a98f

2023-11-15 16:15 UTC, RemiBonnet commented on libs/domains/organizations/data-access/src/lib/domains-organizations-data-access.ts
> +  }),
https://github.com/Qovery/console/pull/957/commits/0d149391e88d4eedad1522e4b0075b175900a98f

2023-11-15 16:21 UTC, merged

2023-11-20 16:38 UTC, RemiBonnet commented
:tada: This PR is included in version 1.65.0 :tada:

The release is available on [GitHub release](https://github.com/Qovery/console/releases/tag/v1.65.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: