Copy menu item
Qovery/console pull request #97
Opened 2022-05-19 12:02 UTC by WilliamTraoreee

# What does this PR do?

Add the possibility to have a button to copy on the clipboard a string on a menu item

<img width="348" alt="image" src="https://user-images.githubusercontent.com/33811490/169288605-a42d1e90-8ab5-403a-a713-a410c40a5028.png">

---

## PR Checklist

### Global

- [x] This PR does not introduce any breaking change
- [ ] This PR introduces breaking change(s) and has been labeled as such
- [x] I have found someone to review this PR and pinged him

### Store

- [ ] This PR introduces new store changes

### NX

- [x] I have run the dep-graph locally and made sure the tree was clean i.e no circular dependencies
- [x] I have followed the library pattern i.e `feature`, `ui`, `data`, `utils`

### Clean Code

- [x] I made sure the code is type safe (no any)
- [ ] I have included a feature flag on my feature, if applicable

2022-05-24 13:57 UTC, bdebon commented on libs/pages/application/ui/src/lib/components/container/container.tsx
> +        copy: link.url || '',
Why not accepting null for copy? In this case if copy is null you just don't show nothing

2022-05-24 13:57 UTC, bdebon commented on libs/shared/ui/src/lib/components/menu/menu-item/menu-item.tsx
> +  copy?: string
Ah here you seems to accept that copy is null

2022-05-30 13:06 UTC, RemiBonnet requested changes
I am agree with the request by Benjamin, and can you hide the button when we don't have link? example here : `/organization/ffffffff-ffff-ffff-ffff-ffffffffffff/project/e0aabc0d-99cb-4867-ad39-332d6162c32c/environment/b91d2eb8-a850-49b5-8626-ade7afc4a28b/application/abbcf976-27a1-4531-9cdd-e4d15d7b2c27/general` 

<img width="374" alt="Capture d’écran 2022-05-30 à 15 04 18" src="https://user-images.githubusercontent.com/533928/170998259-5270f75c-b1db-4e8d-adb0-dfa7cca9607c.png">

Plus, the height of this button has change, can you fix that?

Thanks!

2022-05-31 07:53 UTC, RemiBonnet commented on libs/pages/application/ui/src/lib/components/container/container.tsx
> +  console.log(application)
need to be removed

2022-05-31 07:53 UTC, RemiBonnet commented on libs/pages/application/ui/src/lib/components/container/container.tsx
> +      {application?.links && application.links.items && application.links.items.length !== 0 && linkButtons()}
`application.links.items.length > 0` 

cleaner to have this

2022-05-31 07:53 UTC, RemiBonnet commented on libs/pages/application/ui/src/lib/components/container/container.tsx
> +      {application?.links && application.links.items && application.links.items.length !== 0 && linkButtons()}
`application.links.items.length > 0` 

cleaner to have this

2022-05-31 11:28 UTC, RemiBonnet commented
@WilliamTraoreee ok for merge!

2022-05-31 16:29 UTC, merged

2022-06-22 13:17 UTC, bdebon commented
:tada: This PR is included in version 1.0.0-staging.1 :tada:

The release is available on [GitHub release](https://github.com/Qovery/console/releases/tag/v1.0.0-staging.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-11-17 10:32 UTC, bdebon commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/Qovery/console/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: