feat(services): add Helm support in service pages
Qovery/console pull request #982
Opened 2023-11-23 10:36 UTC by ctjhoa

# What does this PR do?

https://qovery.atlassian.net/browse/FRT-874

2023-11-23 10:36 UTC, acarranoqovery commented
[![Qovery Preview](https://www.qovery.com/images/logo-white.svg)](https://www.qovery.com)
---

Qovery can create a Preview Environment for this PR.
To trigger its creation, please post a comment with one of the following command.

| Command | Blueprint environment |
|---|---|
| /qovery <!-- combo breaker --> preview 28c47145-c8e7-4b9d-8d9e-c65c95b48425 | [staging](https://console.qovery.com/organization/3d542888-3d2c-474a-b1ad-712556db66da/project/a64f6cc1-4e34-433b-b8fd-5359716fb01b/environment/28c47145-c8e7-4b9d-8d9e-c65c95b48425/services/general) |
| /qovery <!-- combo breaker --> preview {all\|UUID1,UUID2,...} | To preview multiple environments |

---

This comment has been generated from [Qovery](https://qovery.com) AI :robot:.
Below, a word from its wisdom :
> Write comments that add new information that doesn’t exist in the code

2023-11-27 10:13 UTC, RemiBonnet requested changes
Hey @ctjhoa thanks !

Here's my feedback, I tried this URL: http://localhost:4200/organization/3d542888-3d2c-474a-b1ad-712556db66da/project/89435f76-990b-4f1a-ae6c-c55d96727a23/environment/7826b8eb-76a1-4758-804a-5e62fa86cf32/application/c6b6ca49-b071-4921-99f9-5c3b8f32b322/general

- Source by git repository are not available
<img width="368" alt="Capture d’écran 2023-11-27 à 11 01 54" src="https://github.com/Qovery/console/assets/533928/e7bbde87-1636-4378-b281-3ef39f5583b5">

- It missing the Helm icon and the version badge have a glitch
<img width="1410" alt="Capture d’écran 2023-11-27 à 11 02 53" src="https://github.com/Qovery/console/assets/533928/a5b2a5b9-dc64-4b68-a6ed-a5995381897f">

- You can implement setting / source / deployment settings, I don't know if you want do that on this PR ? I see the ticket speak about that

2023-11-27 10:13 UTC, RemiBonnet commented on libs/domains/services/feature/src/lib/service-details/service-details.tsx
>                const gitRepository = match(service)
It doesn't work we can't see a git repository source for Helm

2023-11-28 09:31 UTC, RemiBonnet approved these changes

2023-11-28 09:31 UTC, RemiBonnet commented on libs/shared/ui/src/lib/components/icon/icon.tsx
> +      return <HelmServiceIcon {...formattedProps} />
Can you have the same name between HelmService and Helm?

2023-11-28 16:27 UTC, merged

2023-11-29 14:13 UTC, RemiBonnet commented
:tada: This PR is included in version 1.69.0 :tada:

The release is available on [GitHub release](https://github.com/Qovery/console/releases/tag/v1.69.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: