feat(ui): add tabs primitives
Qovery/console pull request #987
Opened 2023-11-24 09:37 UTC by ctjhoa

# What does this PR do?

Related to https://qovery.atlassian.net/browse/FRT-874

![2023-11-24-103641_1920x954_scrot](https://github.com/Qovery/console/assets/1716173/0d7368e5-0424-4fe8-a5cb-a610d08b88e4)

2023-11-24 09:37 UTC, acarranoqovery commented
[![Qovery Preview](https://www.qovery.com/images/logo-white.svg)](https://www.qovery.com)
---

Qovery can create a Preview Environment for this PR.
To trigger its creation, please post a comment with one of the following command.

| Command | Blueprint environment |
|---|---|
| /qovery <!-- combo breaker --> preview 28c47145-c8e7-4b9d-8d9e-c65c95b48425 | [staging](https://console.qovery.com/organization/3d542888-3d2c-474a-b1ad-712556db66da/project/a64f6cc1-4e34-433b-b8fd-5359716fb01b/environment/28c47145-c8e7-4b9d-8d9e-c65c95b48425/services/general) |
| /qovery <!-- combo breaker --> preview {all\|UUID1,UUID2,...} | To preview multiple environments |

---

This comment has been generated from [Qovery](https://qovery.com) AI :robot:.
Below, a word from its wisdom :
> Don’t Sacrifice Readability, you are going to debug it in 6 months

2023-11-24 14:15 UTC, RemiBonnet requested changes

2023-11-24 14:15 UTC, RemiBonnet commented on libs/shared/ui/src/lib/components/tabs-primitives/tabs-primitives.tsx
> +        md: ['text-sm', 'px-3', 'h-[52px]', 'font-medium'],
```suggestion
        md: ['text-sm', 'px-4', 'h-[52px]', 'font-medium'],
```

2023-11-24 14:30 UTC, RemiBonnet approved these changes

2023-11-24 14:40 UTC, merged

2023-11-29 14:13 UTC, RemiBonnet commented
:tada: This PR is included in version 1.69.0 :tada:

The release is available on [GitHub release](https://github.com/Qovery/console/releases/tag/v1.69.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: