feat(ui): add code editor component
Qovery/console pull request #988
Opened 2023-11-24 10:14 UTC by RemiBonnet

# What does this PR do?

- Add code editor component

<img width="1125" alt="Capture d’écran 2023-11-24 à 11 14 59" src="https://github.com/Qovery/console/assets/533928/976254b4-9c02-4007-a208-d8e7831d4513">

---

## PR Checklist

- [ ] This PR introduces breaking change(s) and has been labeled as such
- [ ] This PR introduces new store changes
- [x] I have followed the library pattern i.e `feature`, `ui`, `data`, `utils`
- [x] I made sure the code is type safe (no any)

2023-11-24 10:14 UTC, acarranoqovery commented
[![Qovery Preview](https://www.qovery.com/images/logo-white.svg)](https://www.qovery.com)
---

Qovery can create a Preview Environment for this PR.
To trigger its creation, please post a comment with one of the following command.

| Command | Blueprint environment |
|---|---|
| /qovery <!-- combo breaker --> preview 28c47145-c8e7-4b9d-8d9e-c65c95b48425 | [staging](https://console.qovery.com/organization/3d542888-3d2c-474a-b1ad-712556db66da/project/a64f6cc1-4e34-433b-b8fd-5359716fb01b/environment/28c47145-c8e7-4b9d-8d9e-c65c95b48425/services/general) |
| /qovery <!-- combo breaker --> preview {all\|UUID1,UUID2,...} | To preview multiple environments |

---

This comment has been generated from [Qovery](https://qovery.com) AI :robot:.
Below, a word from its wisdom :
> There are two hard problems in computer science: naming things, cache invalidation and off-by-1 errors

2023-11-24 13:06 UTC, ctjhoa requested changes

2023-11-24 13:06 UTC, ctjhoa commented on libs/shared/ui/src/lib/components/editor/editor.tsx
> +import { Editor as EditMonaco, type EditorProps as EditorMonacoProps } from '@monaco-editor/react'
```suggestion
import { Editor as EditorMonaco, type EditorProps as EditorMonacoProps } from '@monaco-editor/react'
```

2023-11-24 13:06 UTC, ctjhoa commented on libs/shared/ui/src/index.ts
> +export * from './lib/components/editor/editor'
Can we name it `code-editor` in case we have a text editor in the future?

2023-11-24 15:28 UTC, ctjhoa approved these changes

2023-11-24 15:58 UTC, merged

2023-11-29 14:12 UTC, RemiBonnet commented
:tada: This PR is included in version 1.69.0 :tada:

The release is available on [GitHub release](https://github.com/Qovery/console/releases/tag/v1.69.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: